/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DateRangePrayerTimesCalendar400Response
 */
export interface DateRangePrayerTimesCalendar400Response {
    /**
     * 
     * @type {number}
     * @memberof DateRangePrayerTimesCalendar400Response
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof DateRangePrayerTimesCalendar400Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DateRangePrayerTimesCalendar400Response
     */
    data?: string;
}

/**
 * Check if a given object implements the DateRangePrayerTimesCalendar400Response interface.
 */
export function instanceOfDateRangePrayerTimesCalendar400Response(value: object): value is DateRangePrayerTimesCalendar400Response {
    return true;
}

export function DateRangePrayerTimesCalendar400ResponseFromJSON(json: any): DateRangePrayerTimesCalendar400Response {
    return DateRangePrayerTimesCalendar400ResponseFromJSONTyped(json, false);
}

export function DateRangePrayerTimesCalendar400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateRangePrayerTimesCalendar400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function DateRangePrayerTimesCalendar400ResponseToJSON(json: any): DateRangePrayerTimesCalendar400Response {
    return DateRangePrayerTimesCalendar400ResponseToJSONTyped(json, false);
}

export function DateRangePrayerTimesCalendar400ResponseToJSONTyped(value?: DateRangePrayerTimesCalendar400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': value['data'],
    };
}

