/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineObject
     */
    data?: number;
}

/**
 * Check if a given object implements the InlineObject interface.
 */
export function instanceOfInlineObject(value: object): value is InlineObject {
    return true;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function InlineObjectToJSON(json: any): InlineObject {
    return InlineObjectToJSONTyped(json, false);
}

export function InlineObjectToJSONTyped(value?: InlineObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': value['data'],
    };
}

