/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams
 */
export interface Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams {
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams
     */
    shafaq?: string;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataMOONSIGHTINGParams(value: object): value is Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams {
    return true;
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsFromJSON(json: any): Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams {
    return Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams {
    if (json == null) {
        return json;
    }
    return {
        
        'shafaq': json['shafaq'] == null ? undefined : json['shafaq'],
    };
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsToJSON(json: any): Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams {
    return Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsToJSONTyped(value?: Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shafaq': value['shafaq'],
    };
}

