/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataISNAParams
 */
export interface Model200PrayerCalMethodsResponseDataISNAParams {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataISNAParams
     */
    fajr?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataISNAParams
     */
    isha?: number;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataISNAParams interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataISNAParams(value: object): value is Model200PrayerCalMethodsResponseDataISNAParams {
    return true;
}

export function Model200PrayerCalMethodsResponseDataISNAParamsFromJSON(json: any): Model200PrayerCalMethodsResponseDataISNAParams {
    return Model200PrayerCalMethodsResponseDataISNAParamsFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataISNAParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataISNAParams {
    if (json == null) {
        return json;
    }
    return {
        
        'fajr': json['Fajr'] == null ? undefined : json['Fajr'],
        'isha': json['Isha'] == null ? undefined : json['Isha'],
    };
}

export function Model200PrayerCalMethodsResponseDataISNAParamsToJSON(json: any): Model200PrayerCalMethodsResponseDataISNAParams {
    return Model200PrayerCalMethodsResponseDataISNAParamsToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataISNAParamsToJSONTyped(value?: Model200PrayerCalMethodsResponseDataISNAParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Fajr': value['fajr'],
        'Isha': value['isha'],
    };
}

