/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataMOROCCOParams } from './Model200PrayerCalMethodsResponseDataMOROCCOParams.js';
import {
    Model200PrayerCalMethodsResponseDataMOROCCOParamsFromJSON,
    Model200PrayerCalMethodsResponseDataMOROCCOParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMOROCCOParamsToJSON,
    Model200PrayerCalMethodsResponseDataMOROCCOParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMOROCCOParams.js';
import type { Model200PrayerCalMethodsResponseDataMOROCCOLocation } from './Model200PrayerCalMethodsResponseDataMOROCCOLocation.js';
import {
    Model200PrayerCalMethodsResponseDataMOROCCOLocationFromJSON,
    Model200PrayerCalMethodsResponseDataMOROCCOLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMOROCCOLocationToJSON,
    Model200PrayerCalMethodsResponseDataMOROCCOLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMOROCCOLocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataMOROCCO
 */
export interface Model200PrayerCalMethodsResponseDataMOROCCO {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataMOROCCO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataMOROCCO
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMOROCCOParams}
     * @memberof Model200PrayerCalMethodsResponseDataMOROCCO
     */
    params?: Model200PrayerCalMethodsResponseDataMOROCCOParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMOROCCOLocation}
     * @memberof Model200PrayerCalMethodsResponseDataMOROCCO
     */
    location?: Model200PrayerCalMethodsResponseDataMOROCCOLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataMOROCCO interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataMOROCCO(value: object): value is Model200PrayerCalMethodsResponseDataMOROCCO {
    return true;
}

export function Model200PrayerCalMethodsResponseDataMOROCCOFromJSON(json: any): Model200PrayerCalMethodsResponseDataMOROCCO {
    return Model200PrayerCalMethodsResponseDataMOROCCOFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMOROCCOFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataMOROCCO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataMOROCCOParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataMOROCCOLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataMOROCCOToJSON(json: any): Model200PrayerCalMethodsResponseDataMOROCCO {
    return Model200PrayerCalMethodsResponseDataMOROCCOToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMOROCCOToJSONTyped(value?: Model200PrayerCalMethodsResponseDataMOROCCO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataMOROCCOParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataMOROCCOLocationToJSON(value['location']),
    };
}

