/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataTEHRANLocation } from './Model200PrayerCalMethodsResponseDataTEHRANLocation.js';
import {
    Model200PrayerCalMethodsResponseDataTEHRANLocationFromJSON,
    Model200PrayerCalMethodsResponseDataTEHRANLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTEHRANLocationToJSON,
    Model200PrayerCalMethodsResponseDataTEHRANLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTEHRANLocation.js';
import type { Model200PrayerCalMethodsResponseDataTEHRANParams } from './Model200PrayerCalMethodsResponseDataTEHRANParams.js';
import {
    Model200PrayerCalMethodsResponseDataTEHRANParamsFromJSON,
    Model200PrayerCalMethodsResponseDataTEHRANParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTEHRANParamsToJSON,
    Model200PrayerCalMethodsResponseDataTEHRANParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTEHRANParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataTEHRAN
 */
export interface Model200PrayerCalMethodsResponseDataTEHRAN {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataTEHRAN
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataTEHRAN
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTEHRANParams}
     * @memberof Model200PrayerCalMethodsResponseDataTEHRAN
     */
    params?: Model200PrayerCalMethodsResponseDataTEHRANParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTEHRANLocation}
     * @memberof Model200PrayerCalMethodsResponseDataTEHRAN
     */
    location?: Model200PrayerCalMethodsResponseDataTEHRANLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataTEHRAN interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataTEHRAN(value: object): value is Model200PrayerCalMethodsResponseDataTEHRAN {
    return true;
}

export function Model200PrayerCalMethodsResponseDataTEHRANFromJSON(json: any): Model200PrayerCalMethodsResponseDataTEHRAN {
    return Model200PrayerCalMethodsResponseDataTEHRANFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataTEHRANFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataTEHRAN {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataTEHRANParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataTEHRANLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataTEHRANToJSON(json: any): Model200PrayerCalMethodsResponseDataTEHRAN {
    return Model200PrayerCalMethodsResponseDataTEHRANToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataTEHRANToJSONTyped(value?: Model200PrayerCalMethodsResponseDataTEHRAN | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataTEHRANParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataTEHRANLocationToJSON(value['location']),
    };
}

