/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataGULFLocation
 */
export interface Model200PrayerCalMethodsResponseDataGULFLocation {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataGULFLocation
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataGULFLocation
     */
    longitude?: number;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataGULFLocation interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataGULFLocation(value: object): value is Model200PrayerCalMethodsResponseDataGULFLocation {
    return true;
}

export function Model200PrayerCalMethodsResponseDataGULFLocationFromJSON(json: any): Model200PrayerCalMethodsResponseDataGULFLocation {
    return Model200PrayerCalMethodsResponseDataGULFLocationFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataGULFLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataGULFLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function Model200PrayerCalMethodsResponseDataGULFLocationToJSON(json: any): Model200PrayerCalMethodsResponseDataGULFLocation {
    return Model200PrayerCalMethodsResponseDataGULFLocationToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataGULFLocationToJSONTyped(value?: Model200PrayerCalMethodsResponseDataGULFLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

