/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesPrayerTimesCalendarMonthResponseDataInner } from './Model200TimesPrayerTimesCalendarMonthResponseDataInner.js';
import {
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSONTyped,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSONTyped,
} from './Model200TimesPrayerTimesCalendarMonthResponseDataInner.js';

/**
 * 
 * @export
 * @interface Model200TimesPrayerTimesCalendarMonthResponse
 */
export interface Model200TimesPrayerTimesCalendarMonthResponse {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesPrayerTimesCalendarMonthResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesPrayerTimesCalendarMonthResponse
     */
    status?: string;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarMonthResponse
     */
    data?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
}

/**
 * Check if a given object implements the Model200TimesPrayerTimesCalendarMonthResponse interface.
 */
export function instanceOfModel200TimesPrayerTimesCalendarMonthResponse(value: object): value is Model200TimesPrayerTimesCalendarMonthResponse {
    return true;
}

export function Model200TimesPrayerTimesCalendarMonthResponseFromJSON(json: any): Model200TimesPrayerTimesCalendarMonthResponse {
    return Model200TimesPrayerTimesCalendarMonthResponseFromJSONTyped(json, false);
}

export function Model200TimesPrayerTimesCalendarMonthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesPrayerTimesCalendarMonthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
    };
}

export function Model200TimesPrayerTimesCalendarMonthResponseToJSON(json: any): Model200TimesPrayerTimesCalendarMonthResponse {
    return Model200TimesPrayerTimesCalendarMonthResponseToJSONTyped(json, false);
}

export function Model200TimesPrayerTimesCalendarMonthResponseToJSONTyped(value?: Model200TimesPrayerTimesCalendarMonthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
    };
}

