/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateGregorianMonth
 */
export interface Model200TimesResponseDataDateGregorianMonth {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataDateGregorianMonth
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorianMonth
     */
    en?: string;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateGregorianMonth interface.
 */
export function instanceOfModel200TimesResponseDataDateGregorianMonth(value: object): value is Model200TimesResponseDataDateGregorianMonth {
    return true;
}

export function Model200TimesResponseDataDateGregorianMonthFromJSON(json: any): Model200TimesResponseDataDateGregorianMonth {
    return Model200TimesResponseDataDateGregorianMonthFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianMonthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateGregorianMonth {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function Model200TimesResponseDataDateGregorianMonthToJSON(json: any): Model200TimesResponseDataDateGregorianMonth {
    return Model200TimesResponseDataDateGregorianMonthToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianMonthToJSONTyped(value?: Model200TimesResponseDataDateGregorianMonth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'en': value['en'],
    };
}

