/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesPrayerTimesCalendarMonthResponseDataInner } from './Model200TimesPrayerTimesCalendarMonthResponseDataInner.js';
import {
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSONTyped,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSONTyped,
} from './Model200TimesPrayerTimesCalendarMonthResponseDataInner.js';

/**
 * 
 * @export
 * @interface Model200TimesPrayerTimesCalendarYearResponseData
 */
export interface Model200TimesPrayerTimesCalendarYearResponseData {
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _1?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _2?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _3?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _4?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _5?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _6?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _7?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _8?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _9?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _10?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _11?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimesPrayerTimesCalendarYearResponseData
     */
    _12?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
}

/**
 * Check if a given object implements the Model200TimesPrayerTimesCalendarYearResponseData interface.
 */
export function instanceOfModel200TimesPrayerTimesCalendarYearResponseData(value: object): value is Model200TimesPrayerTimesCalendarYearResponseData {
    return true;
}

export function Model200TimesPrayerTimesCalendarYearResponseDataFromJSON(json: any): Model200TimesPrayerTimesCalendarYearResponseData {
    return Model200TimesPrayerTimesCalendarYearResponseDataFromJSONTyped(json, false);
}

export function Model200TimesPrayerTimesCalendarYearResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesPrayerTimesCalendarYearResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        '_1': json['1'] == null ? undefined : ((json['1'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_2': json['2'] == null ? undefined : ((json['2'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_3': json['3'] == null ? undefined : ((json['3'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_4': json['4'] == null ? undefined : ((json['4'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_5': json['5'] == null ? undefined : ((json['5'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_6': json['6'] == null ? undefined : ((json['6'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_7': json['7'] == null ? undefined : ((json['7'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_8': json['8'] == null ? undefined : ((json['8'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_9': json['9'] == null ? undefined : ((json['9'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_10': json['10'] == null ? undefined : ((json['10'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_11': json['11'] == null ? undefined : ((json['11'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
        '_12': json['12'] == null ? undefined : ((json['12'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
    };
}

export function Model200TimesPrayerTimesCalendarYearResponseDataToJSON(json: any): Model200TimesPrayerTimesCalendarYearResponseData {
    return Model200TimesPrayerTimesCalendarYearResponseDataToJSONTyped(json, false);
}

export function Model200TimesPrayerTimesCalendarYearResponseDataToJSONTyped(value?: Model200TimesPrayerTimesCalendarYearResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '1': value['_1'] == null ? undefined : ((value['_1'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '2': value['_2'] == null ? undefined : ((value['_2'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '3': value['_3'] == null ? undefined : ((value['_3'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '4': value['_4'] == null ? undefined : ((value['_4'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '5': value['_5'] == null ? undefined : ((value['_5'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '6': value['_6'] == null ? undefined : ((value['_6'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '7': value['_7'] == null ? undefined : ((value['_7'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '8': value['_8'] == null ? undefined : ((value['_8'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '9': value['_9'] == null ? undefined : ((value['_9'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '10': value['_10'] == null ? undefined : ((value['_10'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '11': value['_11'] == null ? undefined : ((value['_11'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
        '12': value['_12'] == null ? undefined : ((value['_12'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
    };
}

