/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataMetaMethodParams } from './Model200TimesResponseDataMetaMethodParams.js';
import {
    Model200TimesResponseDataMetaMethodParamsFromJSON,
    Model200TimesResponseDataMetaMethodParamsFromJSONTyped,
    Model200TimesResponseDataMetaMethodParamsToJSON,
    Model200TimesResponseDataMetaMethodParamsToJSONTyped,
} from './Model200TimesResponseDataMetaMethodParams.js';
import type { Model200PrayerCalMethodsResponseDataTURKEYLocation } from './Model200PrayerCalMethodsResponseDataTURKEYLocation.js';
import {
    Model200PrayerCalMethodsResponseDataTURKEYLocationFromJSON,
    Model200PrayerCalMethodsResponseDataTURKEYLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTURKEYLocationToJSON,
    Model200PrayerCalMethodsResponseDataTURKEYLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTURKEYLocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataTURKEY
 */
export interface Model200PrayerCalMethodsResponseDataTURKEY {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataTURKEY
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataTURKEY
     */
    name?: string;
    /**
     * 
     * @type {Model200TimesResponseDataMetaMethodParams}
     * @memberof Model200PrayerCalMethodsResponseDataTURKEY
     */
    params?: Model200TimesResponseDataMetaMethodParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTURKEYLocation}
     * @memberof Model200PrayerCalMethodsResponseDataTURKEY
     */
    location?: Model200PrayerCalMethodsResponseDataTURKEYLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataTURKEY interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataTURKEY(value: object): value is Model200PrayerCalMethodsResponseDataTURKEY {
    return true;
}

export function Model200PrayerCalMethodsResponseDataTURKEYFromJSON(json: any): Model200PrayerCalMethodsResponseDataTURKEY {
    return Model200PrayerCalMethodsResponseDataTURKEYFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataTURKEYFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataTURKEY {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200TimesResponseDataMetaMethodParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataTURKEYLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataTURKEYToJSON(json: any): Model200PrayerCalMethodsResponseDataTURKEY {
    return Model200PrayerCalMethodsResponseDataTURKEYToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataTURKEYToJSONTyped(value?: Model200PrayerCalMethodsResponseDataTURKEY | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200TimesResponseDataMetaMethodParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataTURKEYLocationToJSON(value['location']),
    };
}

