/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataKARACHIParams } from './Model200PrayerCalMethodsResponseDataKARACHIParams.js';
import {
    Model200PrayerCalMethodsResponseDataKARACHIParamsFromJSON,
    Model200PrayerCalMethodsResponseDataKARACHIParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKARACHIParamsToJSON,
    Model200PrayerCalMethodsResponseDataKARACHIParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKARACHIParams.js';
import type { Model200PrayerCalMethodsResponseDataKARACHILocation } from './Model200PrayerCalMethodsResponseDataKARACHILocation.js';
import {
    Model200PrayerCalMethodsResponseDataKARACHILocationFromJSON,
    Model200PrayerCalMethodsResponseDataKARACHILocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKARACHILocationToJSON,
    Model200PrayerCalMethodsResponseDataKARACHILocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKARACHILocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataKARACHI
 */
export interface Model200PrayerCalMethodsResponseDataKARACHI {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataKARACHI
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataKARACHI
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKARACHIParams}
     * @memberof Model200PrayerCalMethodsResponseDataKARACHI
     */
    params?: Model200PrayerCalMethodsResponseDataKARACHIParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKARACHILocation}
     * @memberof Model200PrayerCalMethodsResponseDataKARACHI
     */
    location?: Model200PrayerCalMethodsResponseDataKARACHILocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataKARACHI interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataKARACHI(value: object): value is Model200PrayerCalMethodsResponseDataKARACHI {
    return true;
}

export function Model200PrayerCalMethodsResponseDataKARACHIFromJSON(json: any): Model200PrayerCalMethodsResponseDataKARACHI {
    return Model200PrayerCalMethodsResponseDataKARACHIFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataKARACHIFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataKARACHI {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataKARACHIParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataKARACHILocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataKARACHIToJSON(json: any): Model200PrayerCalMethodsResponseDataKARACHI {
    return Model200PrayerCalMethodsResponseDataKARACHIToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataKARACHIToJSONTyped(value?: Model200PrayerCalMethodsResponseDataKARACHI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataKARACHIParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataKARACHILocationToJSON(value['location']),
    };
}

