/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataDateHijri } from './Model200TimesResponseDataDateHijri.js';
import {
    Model200TimesResponseDataDateHijriFromJSON,
    Model200TimesResponseDataDateHijriFromJSONTyped,
    Model200TimesResponseDataDateHijriToJSON,
    Model200TimesResponseDataDateHijriToJSONTyped,
} from './Model200TimesResponseDataDateHijri.js';
import type { Model200TimesResponseDataDateGregorian } from './Model200TimesResponseDataDateGregorian.js';
import {
    Model200TimesResponseDataDateGregorianFromJSON,
    Model200TimesResponseDataDateGregorianFromJSONTyped,
    Model200TimesResponseDataDateGregorianToJSON,
    Model200TimesResponseDataDateGregorianToJSONTyped,
} from './Model200TimesResponseDataDateGregorian.js';

/**
 * 
 * @export
 * @interface ModelDate
 */
export interface ModelDate {
    /**
     * 
     * @type {string}
     * @memberof ModelDate
     */
    readable?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDate
     */
    timestamp?: string;
    /**
     * 
     * @type {Model200TimesResponseDataDateHijri}
     * @memberof ModelDate
     */
    hijri?: Model200TimesResponseDataDateHijri;
    /**
     * 
     * @type {Model200TimesResponseDataDateGregorian}
     * @memberof ModelDate
     */
    gregorian?: Model200TimesResponseDataDateGregorian;
}

/**
 * Check if a given object implements the ModelDate interface.
 */
export function instanceOfModelDate(value: object): value is ModelDate {
    return true;
}

export function ModelDateFromJSON(json: any): ModelDate {
    return ModelDateFromJSONTyped(json, false);
}

export function ModelDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDate {
    if (json == null) {
        return json;
    }
    return {
        
        'readable': json['readable'] == null ? undefined : json['readable'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'hijri': json['hijri'] == null ? undefined : Model200TimesResponseDataDateHijriFromJSON(json['hijri']),
        'gregorian': json['gregorian'] == null ? undefined : Model200TimesResponseDataDateGregorianFromJSON(json['gregorian']),
    };
}

export function ModelDateToJSON(json: any): ModelDate {
    return ModelDateToJSONTyped(json, false);
}

export function ModelDateToJSONTyped(value?: ModelDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'readable': value['readable'],
        'timestamp': value['timestamp'],
        'hijri': Model200TimesResponseDataDateHijriToJSON(value['hijri']),
        'gregorian': Model200TimesResponseDataDateGregorianToJSON(value['gregorian']),
    };
}

