/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesPrayerTimesCalendarMonthResponseDataInner } from './Model200TimesPrayerTimesCalendarMonthResponseDataInner.js';
import {
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSONTyped,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON,
    Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSONTyped,
} from './Model200TimesPrayerTimesCalendarMonthResponseDataInner.js';

/**
 * 
 * @export
 * @interface Model200TimingPartialMonthResponse
 */
export interface Model200TimingPartialMonthResponse {
    /**
     * 
     * @type {Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>}
     * @memberof Model200TimingPartialMonthResponse
     */
    _1?: Array<Model200TimesPrayerTimesCalendarMonthResponseDataInner>;
}

/**
 * Check if a given object implements the Model200TimingPartialMonthResponse interface.
 */
export function instanceOfModel200TimingPartialMonthResponse(value: object): value is Model200TimingPartialMonthResponse {
    return true;
}

export function Model200TimingPartialMonthResponseFromJSON(json: any): Model200TimingPartialMonthResponse {
    return Model200TimingPartialMonthResponseFromJSONTyped(json, false);
}

export function Model200TimingPartialMonthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimingPartialMonthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '_1': json['1'] == null ? undefined : ((json['1'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON)),
    };
}

export function Model200TimingPartialMonthResponseToJSON(json: any): Model200TimingPartialMonthResponse {
    return Model200TimingPartialMonthResponseToJSONTyped(json, false);
}

export function Model200TimingPartialMonthResponseToJSONTyped(value?: Model200TimingPartialMonthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '1': value['_1'] == null ? undefined : ((value['_1'] as Array<any>).map(Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON)),
    };
}

