/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataRUSSIALocation } from './Model200PrayerCalMethodsResponseDataRUSSIALocation.js';
import {
    Model200PrayerCalMethodsResponseDataRUSSIALocationFromJSON,
    Model200PrayerCalMethodsResponseDataRUSSIALocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataRUSSIALocationToJSON,
    Model200PrayerCalMethodsResponseDataRUSSIALocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataRUSSIALocation.js';
import type { Model200PrayerCalMethodsResponseDataRUSSIAParams } from './Model200PrayerCalMethodsResponseDataRUSSIAParams.js';
import {
    Model200PrayerCalMethodsResponseDataRUSSIAParamsFromJSON,
    Model200PrayerCalMethodsResponseDataRUSSIAParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataRUSSIAParamsToJSON,
    Model200PrayerCalMethodsResponseDataRUSSIAParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataRUSSIAParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataRUSSIA
 */
export interface Model200PrayerCalMethodsResponseDataRUSSIA {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataRUSSIA
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataRUSSIA
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataRUSSIAParams}
     * @memberof Model200PrayerCalMethodsResponseDataRUSSIA
     */
    params?: Model200PrayerCalMethodsResponseDataRUSSIAParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataRUSSIALocation}
     * @memberof Model200PrayerCalMethodsResponseDataRUSSIA
     */
    location?: Model200PrayerCalMethodsResponseDataRUSSIALocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataRUSSIA interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataRUSSIA(value: object): value is Model200PrayerCalMethodsResponseDataRUSSIA {
    return true;
}

export function Model200PrayerCalMethodsResponseDataRUSSIAFromJSON(json: any): Model200PrayerCalMethodsResponseDataRUSSIA {
    return Model200PrayerCalMethodsResponseDataRUSSIAFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataRUSSIAFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataRUSSIA {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataRUSSIAParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataRUSSIALocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataRUSSIAToJSON(json: any): Model200PrayerCalMethodsResponseDataRUSSIA {
    return Model200PrayerCalMethodsResponseDataRUSSIAToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataRUSSIAToJSONTyped(value?: Model200PrayerCalMethodsResponseDataRUSSIA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataRUSSIAParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataRUSSIALocationToJSON(value['location']),
    };
}

