/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateHijriMonth
 */
export interface Model200TimesResponseDataDateHijriMonth {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataDateHijriMonth
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijriMonth
     */
    en?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijriMonth
     */
    ar?: string;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataDateHijriMonth
     */
    days?: number;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateHijriMonth interface.
 */
export function instanceOfModel200TimesResponseDataDateHijriMonth(value: object): value is Model200TimesResponseDataDateHijriMonth {
    return true;
}

export function Model200TimesResponseDataDateHijriMonthFromJSON(json: any): Model200TimesResponseDataDateHijriMonth {
    return Model200TimesResponseDataDateHijriMonthFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateHijriMonthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateHijriMonth {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'en': json['en'] == null ? undefined : json['en'],
        'ar': json['ar'] == null ? undefined : json['ar'],
        'days': json['days'] == null ? undefined : json['days'],
    };
}

export function Model200TimesResponseDataDateHijriMonthToJSON(json: any): Model200TimesResponseDataDateHijriMonth {
    return Model200TimesResponseDataDateHijriMonthToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateHijriMonthToJSONTyped(value?: Model200TimesResponseDataDateHijriMonth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'en': value['en'],
        'ar': value['ar'],
        'days': value['days'],
    };
}

