/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataDate } from './Model200TimesResponseDataDate.js';
import {
    Model200TimesResponseDataDateFromJSON,
    Model200TimesResponseDataDateFromJSONTyped,
    Model200TimesResponseDataDateToJSON,
    Model200TimesResponseDataDateToJSONTyped,
} from './Model200TimesResponseDataDate.js';
import type { Model200TimesResponseDataMeta } from './Model200TimesResponseDataMeta.js';
import {
    Model200TimesResponseDataMetaFromJSON,
    Model200TimesResponseDataMetaFromJSONTyped,
    Model200TimesResponseDataMetaToJSON,
    Model200TimesResponseDataMetaToJSONTyped,
} from './Model200TimesResponseDataMeta.js';
import type { Model200TimesResponseDataTimings } from './Model200TimesResponseDataTimings.js';
import {
    Model200TimesResponseDataTimingsFromJSON,
    Model200TimesResponseDataTimingsFromJSONTyped,
    Model200TimesResponseDataTimingsToJSON,
    Model200TimesResponseDataTimingsToJSONTyped,
} from './Model200TimesResponseDataTimings.js';

/**
 * 
 * @export
 * @interface Model200TimesResponseData
 */
export interface Model200TimesResponseData {
    /**
     * 
     * @type {Model200TimesResponseDataTimings}
     * @memberof Model200TimesResponseData
     */
    timings?: Model200TimesResponseDataTimings;
    /**
     * 
     * @type {Model200TimesResponseDataDate}
     * @memberof Model200TimesResponseData
     */
    date?: Model200TimesResponseDataDate;
    /**
     * 
     * @type {Model200TimesResponseDataMeta}
     * @memberof Model200TimesResponseData
     */
    meta?: Model200TimesResponseDataMeta;
}

/**
 * Check if a given object implements the Model200TimesResponseData interface.
 */
export function instanceOfModel200TimesResponseData(value: object): value is Model200TimesResponseData {
    return true;
}

export function Model200TimesResponseDataFromJSON(json: any): Model200TimesResponseData {
    return Model200TimesResponseDataFromJSONTyped(json, false);
}

export function Model200TimesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'timings': json['timings'] == null ? undefined : Model200TimesResponseDataTimingsFromJSON(json['timings']),
        'date': json['date'] == null ? undefined : Model200TimesResponseDataDateFromJSON(json['date']),
        'meta': json['meta'] == null ? undefined : Model200TimesResponseDataMetaFromJSON(json['meta']),
    };
}

export function Model200TimesResponseDataToJSON(json: any): Model200TimesResponseData {
    return Model200TimesResponseDataToJSONTyped(json, false);
}

export function Model200TimesResponseDataToJSONTyped(value?: Model200TimesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timings': Model200TimesResponseDataTimingsToJSON(value['timings']),
        'date': Model200TimesResponseDataDateToJSON(value['date']),
        'meta': Model200TimesResponseDataMetaToJSON(value['meta']),
    };
}

