/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesNextPrayerResponseDataTimings
 */
export interface Model200TimesNextPrayerResponseDataTimings {
    /**
     * 
     * @type {string}
     * @memberof Model200TimesNextPrayerResponseDataTimings
     */
    dhuhr?: string;
}

/**
 * Check if a given object implements the Model200TimesNextPrayerResponseDataTimings interface.
 */
export function instanceOfModel200TimesNextPrayerResponseDataTimings(value: object): value is Model200TimesNextPrayerResponseDataTimings {
    return true;
}

export function Model200TimesNextPrayerResponseDataTimingsFromJSON(json: any): Model200TimesNextPrayerResponseDataTimings {
    return Model200TimesNextPrayerResponseDataTimingsFromJSONTyped(json, false);
}

export function Model200TimesNextPrayerResponseDataTimingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesNextPrayerResponseDataTimings {
    if (json == null) {
        return json;
    }
    return {
        
        'dhuhr': json['Dhuhr'] == null ? undefined : json['Dhuhr'],
    };
}

export function Model200TimesNextPrayerResponseDataTimingsToJSON(json: any): Model200TimesNextPrayerResponseDataTimings {
    return Model200TimesNextPrayerResponseDataTimingsToJSONTyped(json, false);
}

export function Model200TimesNextPrayerResponseDataTimingsToJSONTyped(value?: Model200TimesNextPrayerResponseDataTimings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Dhuhr': value['dhuhr'],
    };
}

