/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataDateGregorianMonth } from './Model200TimesResponseDataDateGregorianMonth.js';
import {
    Model200TimesResponseDataDateGregorianMonthFromJSON,
    Model200TimesResponseDataDateGregorianMonthFromJSONTyped,
    Model200TimesResponseDataDateGregorianMonthToJSON,
    Model200TimesResponseDataDateGregorianMonthToJSONTyped,
} from './Model200TimesResponseDataDateGregorianMonth.js';
import type { Model200TimesResponseDataDateGregorianDesignation } from './Model200TimesResponseDataDateGregorianDesignation.js';
import {
    Model200TimesResponseDataDateGregorianDesignationFromJSON,
    Model200TimesResponseDataDateGregorianDesignationFromJSONTyped,
    Model200TimesResponseDataDateGregorianDesignationToJSON,
    Model200TimesResponseDataDateGregorianDesignationToJSONTyped,
} from './Model200TimesResponseDataDateGregorianDesignation.js';
import type { Model200TimesResponseDataDateGregorianWeekday } from './Model200TimesResponseDataDateGregorianWeekday.js';
import {
    Model200TimesResponseDataDateGregorianWeekdayFromJSON,
    Model200TimesResponseDataDateGregorianWeekdayFromJSONTyped,
    Model200TimesResponseDataDateGregorianWeekdayToJSON,
    Model200TimesResponseDataDateGregorianWeekdayToJSONTyped,
} from './Model200TimesResponseDataDateGregorianWeekday.js';

/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateGregorian
 */
export interface Model200TimesResponseDataDateGregorian {
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    format?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    day?: string;
    /**
     * 
     * @type {Model200TimesResponseDataDateGregorianWeekday}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    weekday?: Model200TimesResponseDataDateGregorianWeekday;
    /**
     * 
     * @type {Model200TimesResponseDataDateGregorianMonth}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    month?: Model200TimesResponseDataDateGregorianMonth;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    year?: string;
    /**
     * 
     * @type {Model200TimesResponseDataDateGregorianDesignation}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    designation?: Model200TimesResponseDataDateGregorianDesignation;
    /**
     * 
     * @type {boolean}
     * @memberof Model200TimesResponseDataDateGregorian
     */
    lunarSighting?: boolean;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateGregorian interface.
 */
export function instanceOfModel200TimesResponseDataDateGregorian(value: object): value is Model200TimesResponseDataDateGregorian {
    return true;
}

export function Model200TimesResponseDataDateGregorianFromJSON(json: any): Model200TimesResponseDataDateGregorian {
    return Model200TimesResponseDataDateGregorianFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateGregorian {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'format': json['format'] == null ? undefined : json['format'],
        'day': json['day'] == null ? undefined : json['day'],
        'weekday': json['weekday'] == null ? undefined : Model200TimesResponseDataDateGregorianWeekdayFromJSON(json['weekday']),
        'month': json['month'] == null ? undefined : Model200TimesResponseDataDateGregorianMonthFromJSON(json['month']),
        'year': json['year'] == null ? undefined : json['year'],
        'designation': json['designation'] == null ? undefined : Model200TimesResponseDataDateGregorianDesignationFromJSON(json['designation']),
        'lunarSighting': json['lunarSighting'] == null ? undefined : json['lunarSighting'],
    };
}

export function Model200TimesResponseDataDateGregorianToJSON(json: any): Model200TimesResponseDataDateGregorian {
    return Model200TimesResponseDataDateGregorianToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianToJSONTyped(value?: Model200TimesResponseDataDateGregorian | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'format': value['format'],
        'day': value['day'],
        'weekday': Model200TimesResponseDataDateGregorianWeekdayToJSON(value['weekday']),
        'month': Model200TimesResponseDataDateGregorianMonthToJSON(value['month']),
        'year': value['year'],
        'designation': Model200TimesResponseDataDateGregorianDesignationToJSON(value['designation']),
        'lunarSighting': value['lunarSighting'],
    };
}

