/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataDUBAILocation } from './Model200PrayerCalMethodsResponseDataDUBAILocation.js';
import {
    Model200PrayerCalMethodsResponseDataDUBAILocationFromJSON,
    Model200PrayerCalMethodsResponseDataDUBAILocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataDUBAILocationToJSON,
    Model200PrayerCalMethodsResponseDataDUBAILocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataDUBAILocation.js';
import type { Model200PrayerCalMethodsResponseDataDUBAIParams } from './Model200PrayerCalMethodsResponseDataDUBAIParams.js';
import {
    Model200PrayerCalMethodsResponseDataDUBAIParamsFromJSON,
    Model200PrayerCalMethodsResponseDataDUBAIParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataDUBAIParamsToJSON,
    Model200PrayerCalMethodsResponseDataDUBAIParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataDUBAIParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataDUBAI
 */
export interface Model200PrayerCalMethodsResponseDataDUBAI {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataDUBAI
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataDUBAI
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataDUBAIParams}
     * @memberof Model200PrayerCalMethodsResponseDataDUBAI
     */
    params?: Model200PrayerCalMethodsResponseDataDUBAIParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataDUBAILocation}
     * @memberof Model200PrayerCalMethodsResponseDataDUBAI
     */
    location?: Model200PrayerCalMethodsResponseDataDUBAILocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataDUBAI interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataDUBAI(value: object): value is Model200PrayerCalMethodsResponseDataDUBAI {
    return true;
}

export function Model200PrayerCalMethodsResponseDataDUBAIFromJSON(json: any): Model200PrayerCalMethodsResponseDataDUBAI {
    return Model200PrayerCalMethodsResponseDataDUBAIFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataDUBAIFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataDUBAI {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataDUBAIParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataDUBAILocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataDUBAIToJSON(json: any): Model200PrayerCalMethodsResponseDataDUBAI {
    return Model200PrayerCalMethodsResponseDataDUBAIToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataDUBAIToJSONTyped(value?: Model200PrayerCalMethodsResponseDataDUBAI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataDUBAIParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataDUBAILocationToJSON(value['location']),
    };
}

