/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateGregorianWeekday
 */
export interface Model200TimesResponseDataDateGregorianWeekday {
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorianWeekday
     */
    en?: string;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateGregorianWeekday interface.
 */
export function instanceOfModel200TimesResponseDataDateGregorianWeekday(value: object): value is Model200TimesResponseDataDateGregorianWeekday {
    return true;
}

export function Model200TimesResponseDataDateGregorianWeekdayFromJSON(json: any): Model200TimesResponseDataDateGregorianWeekday {
    return Model200TimesResponseDataDateGregorianWeekdayFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianWeekdayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateGregorianWeekday {
    if (json == null) {
        return json;
    }
    return {
        
        'en': json['en'] == null ? undefined : json['en'],
    };
}

export function Model200TimesResponseDataDateGregorianWeekdayToJSON(json: any): Model200TimesResponseDataDateGregorianWeekday {
    return Model200TimesResponseDataDateGregorianWeekdayToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianWeekdayToJSONTyped(value?: Model200TimesResponseDataDateGregorianWeekday | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'en': value['en'],
    };
}

