/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateGregorianDesignation
 */
export interface Model200TimesResponseDataDateGregorianDesignation {
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorianDesignation
     */
    abbreviated?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateGregorianDesignation
     */
    expanded?: string;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateGregorianDesignation interface.
 */
export function instanceOfModel200TimesResponseDataDateGregorianDesignation(value: object): value is Model200TimesResponseDataDateGregorianDesignation {
    return true;
}

export function Model200TimesResponseDataDateGregorianDesignationFromJSON(json: any): Model200TimesResponseDataDateGregorianDesignation {
    return Model200TimesResponseDataDateGregorianDesignationFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianDesignationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateGregorianDesignation {
    if (json == null) {
        return json;
    }
    return {
        
        'abbreviated': json['abbreviated'] == null ? undefined : json['abbreviated'],
        'expanded': json['expanded'] == null ? undefined : json['expanded'],
    };
}

export function Model200TimesResponseDataDateGregorianDesignationToJSON(json: any): Model200TimesResponseDataDateGregorianDesignation {
    return Model200TimesResponseDataDateGregorianDesignationToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateGregorianDesignationToJSONTyped(value?: Model200TimesResponseDataDateGregorianDesignation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abbreviated': value['abbreviated'],
        'expanded': value['expanded'],
    };
}

