/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Timings } from './Timings.js';
import {
    TimingsFromJSON,
    TimingsFromJSONTyped,
    TimingsToJSON,
    TimingsToJSONTyped,
} from './Timings.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';

/**
 * 
 * @export
 * @interface Model200TimesPrayerTimesCalendarMonthResponseDataInner
 */
export interface Model200TimesPrayerTimesCalendarMonthResponseDataInner {
    /**
     * 
     * @type {Timings}
     * @memberof Model200TimesPrayerTimesCalendarMonthResponseDataInner
     */
    timings?: Timings;
    /**
     * 
     * @type {Date}
     * @memberof Model200TimesPrayerTimesCalendarMonthResponseDataInner
     */
    date?: Date;
    /**
     * 
     * @type {Meta}
     * @memberof Model200TimesPrayerTimesCalendarMonthResponseDataInner
     */
    meta?: Meta;
}

/**
 * Check if a given object implements the Model200TimesPrayerTimesCalendarMonthResponseDataInner interface.
 */
export function instanceOfModel200TimesPrayerTimesCalendarMonthResponseDataInner(value: object): value is Model200TimesPrayerTimesCalendarMonthResponseDataInner {
    return true;
}

export function Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSON(json: any): Model200TimesPrayerTimesCalendarMonthResponseDataInner {
    return Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSONTyped(json, false);
}

export function Model200TimesPrayerTimesCalendarMonthResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesPrayerTimesCalendarMonthResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timings': json['timings'] == null ? undefined : TimingsFromJSON(json['timings']),
        'date': json['date'] == null ? undefined : json['date'],
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSON(json: any): Model200TimesPrayerTimesCalendarMonthResponseDataInner {
    return Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSONTyped(json, false);
}

export function Model200TimesPrayerTimesCalendarMonthResponseDataInnerToJSONTyped(value?: Model200TimesPrayerTimesCalendarMonthResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timings': TimingsToJSON(value['timings']),
        'date': value['date'],
        'meta': MetaToJSON(value['meta']),
    };
}

