/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateHijriWeekday
 */
export interface Model200TimesResponseDataDateHijriWeekday {
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijriWeekday
     */
    en?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijriWeekday
     */
    ar?: string;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateHijriWeekday interface.
 */
export function instanceOfModel200TimesResponseDataDateHijriWeekday(value: object): value is Model200TimesResponseDataDateHijriWeekday {
    return true;
}

export function Model200TimesResponseDataDateHijriWeekdayFromJSON(json: any): Model200TimesResponseDataDateHijriWeekday {
    return Model200TimesResponseDataDateHijriWeekdayFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateHijriWeekdayFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateHijriWeekday {
    if (json == null) {
        return json;
    }
    return {
        
        'en': json['en'] == null ? undefined : json['en'],
        'ar': json['ar'] == null ? undefined : json['ar'],
    };
}

export function Model200TimesResponseDataDateHijriWeekdayToJSON(json: any): Model200TimesResponseDataDateHijriWeekday {
    return Model200TimesResponseDataDateHijriWeekdayToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateHijriWeekdayToJSONTyped(value?: Model200TimesResponseDataDateHijriWeekday | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'en': value['en'],
        'ar': value['ar'],
    };
}

