/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200TimesResponseDataMetaOffset
 */
export interface Model200TimesResponseDataMetaOffset {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    imsak?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    fajr?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    sunrise?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    dhuhr?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    asr?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    sunset?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    maghrib?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    isha?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaOffset
     */
    midnight?: number;
}

/**
 * Check if a given object implements the Model200TimesResponseDataMetaOffset interface.
 */
export function instanceOfModel200TimesResponseDataMetaOffset(value: object): value is Model200TimesResponseDataMetaOffset {
    return true;
}

export function Model200TimesResponseDataMetaOffsetFromJSON(json: any): Model200TimesResponseDataMetaOffset {
    return Model200TimesResponseDataMetaOffsetFromJSONTyped(json, false);
}

export function Model200TimesResponseDataMetaOffsetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataMetaOffset {
    if (json == null) {
        return json;
    }
    return {
        
        'imsak': json['Imsak'] == null ? undefined : json['Imsak'],
        'fajr': json['Fajr'] == null ? undefined : json['Fajr'],
        'sunrise': json['Sunrise'] == null ? undefined : json['Sunrise'],
        'dhuhr': json['Dhuhr'] == null ? undefined : json['Dhuhr'],
        'asr': json['Asr'] == null ? undefined : json['Asr'],
        'sunset': json['Sunset'] == null ? undefined : json['Sunset'],
        'maghrib': json['Maghrib'] == null ? undefined : json['Maghrib'],
        'isha': json['Isha'] == null ? undefined : json['Isha'],
        'midnight': json['Midnight'] == null ? undefined : json['Midnight'],
    };
}

export function Model200TimesResponseDataMetaOffsetToJSON(json: any): Model200TimesResponseDataMetaOffset {
    return Model200TimesResponseDataMetaOffsetToJSONTyped(json, false);
}

export function Model200TimesResponseDataMetaOffsetToJSONTyped(value?: Model200TimesResponseDataMetaOffset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Imsak': value['imsak'],
        'Fajr': value['fajr'],
        'Sunrise': value['sunrise'],
        'Dhuhr': value['dhuhr'],
        'Asr': value['asr'],
        'Sunset': value['sunset'],
        'Maghrib': value['maghrib'],
        'Isha': value['isha'],
        'Midnight': value['midnight'],
    };
}

