/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams } from './Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams.js';
import {
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsFromJSON,
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsToJSON,
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataMOONSIGHTING
 */
export interface Model200PrayerCalMethodsResponseDataMOONSIGHTING {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataMOONSIGHTING
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataMOONSIGHTING
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams}
     * @memberof Model200PrayerCalMethodsResponseDataMOONSIGHTING
     */
    params?: Model200PrayerCalMethodsResponseDataMOONSIGHTINGParams;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataMOONSIGHTING interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataMOONSIGHTING(value: object): value is Model200PrayerCalMethodsResponseDataMOONSIGHTING {
    return true;
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGFromJSON(json: any): Model200PrayerCalMethodsResponseDataMOONSIGHTING {
    return Model200PrayerCalMethodsResponseDataMOONSIGHTINGFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataMOONSIGHTING {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsFromJSON(json['params']),
    };
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGToJSON(json: any): Model200PrayerCalMethodsResponseDataMOONSIGHTING {
    return Model200PrayerCalMethodsResponseDataMOONSIGHTINGToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMOONSIGHTINGToJSONTyped(value?: Model200PrayerCalMethodsResponseDataMOONSIGHTING | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataMOONSIGHTINGParamsToJSON(value['params']),
    };
}

