/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataJAFARI } from './Model200PrayerCalMethodsResponseDataJAFARI.js';
import {
    Model200PrayerCalMethodsResponseDataJAFARIFromJSON,
    Model200PrayerCalMethodsResponseDataJAFARIFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJAFARIToJSON,
    Model200PrayerCalMethodsResponseDataJAFARIToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJAFARI.js';
import type { Model200PrayerCalMethodsResponseDataEGYPT } from './Model200PrayerCalMethodsResponseDataEGYPT.js';
import {
    Model200PrayerCalMethodsResponseDataEGYPTFromJSON,
    Model200PrayerCalMethodsResponseDataEGYPTFromJSONTyped,
    Model200PrayerCalMethodsResponseDataEGYPTToJSON,
    Model200PrayerCalMethodsResponseDataEGYPTToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataEGYPT.js';
import type { Model200PrayerCalMethodsResponseDataSINGAPORE } from './Model200PrayerCalMethodsResponseDataSINGAPORE.js';
import {
    Model200PrayerCalMethodsResponseDataSINGAPOREFromJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREFromJSONTyped,
    Model200PrayerCalMethodsResponseDataSINGAPOREToJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataSINGAPORE.js';
import type { Model200PrayerCalMethodsResponseDataJAKIM } from './Model200PrayerCalMethodsResponseDataJAKIM.js';
import {
    Model200PrayerCalMethodsResponseDataJAKIMFromJSON,
    Model200PrayerCalMethodsResponseDataJAKIMFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJAKIMToJSON,
    Model200PrayerCalMethodsResponseDataJAKIMToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJAKIM.js';
import type { Model200PrayerCalMethodsResponseDataDUBAI } from './Model200PrayerCalMethodsResponseDataDUBAI.js';
import {
    Model200PrayerCalMethodsResponseDataDUBAIFromJSON,
    Model200PrayerCalMethodsResponseDataDUBAIFromJSONTyped,
    Model200PrayerCalMethodsResponseDataDUBAIToJSON,
    Model200PrayerCalMethodsResponseDataDUBAIToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataDUBAI.js';
import type { Model200PrayerCalMethodsResponseDataKARACHI } from './Model200PrayerCalMethodsResponseDataKARACHI.js';
import {
    Model200PrayerCalMethodsResponseDataKARACHIFromJSON,
    Model200PrayerCalMethodsResponseDataKARACHIFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKARACHIToJSON,
    Model200PrayerCalMethodsResponseDataKARACHIToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKARACHI.js';
import type { Model200PrayerCalMethodsResponseDataRUSSIA } from './Model200PrayerCalMethodsResponseDataRUSSIA.js';
import {
    Model200PrayerCalMethodsResponseDataRUSSIAFromJSON,
    Model200PrayerCalMethodsResponseDataRUSSIAFromJSONTyped,
    Model200PrayerCalMethodsResponseDataRUSSIAToJSON,
    Model200PrayerCalMethodsResponseDataRUSSIAToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataRUSSIA.js';
import type { Model200PrayerCalMethodsResponseDataCUSTOM } from './Model200PrayerCalMethodsResponseDataCUSTOM.js';
import {
    Model200PrayerCalMethodsResponseDataCUSTOMFromJSON,
    Model200PrayerCalMethodsResponseDataCUSTOMFromJSONTyped,
    Model200PrayerCalMethodsResponseDataCUSTOMToJSON,
    Model200PrayerCalMethodsResponseDataCUSTOMToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataCUSTOM.js';
import type { Model200PrayerCalMethodsResponseDataGULF } from './Model200PrayerCalMethodsResponseDataGULF.js';
import {
    Model200PrayerCalMethodsResponseDataGULFFromJSON,
    Model200PrayerCalMethodsResponseDataGULFFromJSONTyped,
    Model200PrayerCalMethodsResponseDataGULFToJSON,
    Model200PrayerCalMethodsResponseDataGULFToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataGULF.js';
import type { Model200PrayerCalMethodsResponseDataMOROCCO } from './Model200PrayerCalMethodsResponseDataMOROCCO.js';
import {
    Model200PrayerCalMethodsResponseDataMOROCCOFromJSON,
    Model200PrayerCalMethodsResponseDataMOROCCOFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMOROCCOToJSON,
    Model200PrayerCalMethodsResponseDataMOROCCOToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMOROCCO.js';
import type { Model200PrayerCalMethodsResponseDataTEHRAN } from './Model200PrayerCalMethodsResponseDataTEHRAN.js';
import {
    Model200PrayerCalMethodsResponseDataTEHRANFromJSON,
    Model200PrayerCalMethodsResponseDataTEHRANFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTEHRANToJSON,
    Model200PrayerCalMethodsResponseDataTEHRANToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTEHRAN.js';
import type { Model200PrayerCalMethodsResponseDataTURKEY } from './Model200PrayerCalMethodsResponseDataTURKEY.js';
import {
    Model200PrayerCalMethodsResponseDataTURKEYFromJSON,
    Model200PrayerCalMethodsResponseDataTURKEYFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTURKEYToJSON,
    Model200PrayerCalMethodsResponseDataTURKEYToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTURKEY.js';
import type { Model200PrayerCalMethodsResponseDataISNA } from './Model200PrayerCalMethodsResponseDataISNA.js';
import {
    Model200PrayerCalMethodsResponseDataISNAFromJSON,
    Model200PrayerCalMethodsResponseDataISNAFromJSONTyped,
    Model200PrayerCalMethodsResponseDataISNAToJSON,
    Model200PrayerCalMethodsResponseDataISNAToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataISNA.js';
import type { Model200PrayerCalMethodsResponseDataALGERIA } from './Model200PrayerCalMethodsResponseDataALGERIA.js';
import {
    Model200PrayerCalMethodsResponseDataALGERIAFromJSON,
    Model200PrayerCalMethodsResponseDataALGERIAFromJSONTyped,
    Model200PrayerCalMethodsResponseDataALGERIAToJSON,
    Model200PrayerCalMethodsResponseDataALGERIAToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataALGERIA.js';
import type { Model200PrayerCalMethodsResponseDataJORDAN } from './Model200PrayerCalMethodsResponseDataJORDAN.js';
import {
    Model200PrayerCalMethodsResponseDataJORDANFromJSON,
    Model200PrayerCalMethodsResponseDataJORDANFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJORDANToJSON,
    Model200PrayerCalMethodsResponseDataJORDANToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJORDAN.js';
import type { Model200PrayerCalMethodsResponseDataKEMENAG } from './Model200PrayerCalMethodsResponseDataKEMENAG.js';
import {
    Model200PrayerCalMethodsResponseDataKEMENAGFromJSON,
    Model200PrayerCalMethodsResponseDataKEMENAGFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKEMENAGToJSON,
    Model200PrayerCalMethodsResponseDataKEMENAGToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKEMENAG.js';
import type { Model200PrayerCalMethodsResponseDataMAKKAH } from './Model200PrayerCalMethodsResponseDataMAKKAH.js';
import {
    Model200PrayerCalMethodsResponseDataMAKKAHFromJSON,
    Model200PrayerCalMethodsResponseDataMAKKAHFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMAKKAHToJSON,
    Model200PrayerCalMethodsResponseDataMAKKAHToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMAKKAH.js';
import type { Model200PrayerCalMethodsResponseDataMOONSIGHTING } from './Model200PrayerCalMethodsResponseDataMOONSIGHTING.js';
import {
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGFromJSON,
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGToJSON,
    Model200PrayerCalMethodsResponseDataMOONSIGHTINGToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMOONSIGHTING.js';
import type { Model200PrayerCalMethodsResponseDataQATAR } from './Model200PrayerCalMethodsResponseDataQATAR.js';
import {
    Model200PrayerCalMethodsResponseDataQATARFromJSON,
    Model200PrayerCalMethodsResponseDataQATARFromJSONTyped,
    Model200PrayerCalMethodsResponseDataQATARToJSON,
    Model200PrayerCalMethodsResponseDataQATARToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataQATAR.js';
import type { Model200PrayerCalMethodsResponseDataFRANCE } from './Model200PrayerCalMethodsResponseDataFRANCE.js';
import {
    Model200PrayerCalMethodsResponseDataFRANCEFromJSON,
    Model200PrayerCalMethodsResponseDataFRANCEFromJSONTyped,
    Model200PrayerCalMethodsResponseDataFRANCEToJSON,
    Model200PrayerCalMethodsResponseDataFRANCEToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataFRANCE.js';
import type { Model200PrayerCalMethodsResponseDataKUWAIT } from './Model200PrayerCalMethodsResponseDataKUWAIT.js';
import {
    Model200PrayerCalMethodsResponseDataKUWAITFromJSON,
    Model200PrayerCalMethodsResponseDataKUWAITFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKUWAITToJSON,
    Model200PrayerCalMethodsResponseDataKUWAITToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKUWAIT.js';
import type { Model200PrayerCalMethodsResponseDataTUNISIA } from './Model200PrayerCalMethodsResponseDataTUNISIA.js';
import {
    Model200PrayerCalMethodsResponseDataTUNISIAFromJSON,
    Model200PrayerCalMethodsResponseDataTUNISIAFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTUNISIAToJSON,
    Model200PrayerCalMethodsResponseDataTUNISIAToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTUNISIA.js';
import type { Model200PrayerCalMethodsResponseDataPORTUGAL } from './Model200PrayerCalMethodsResponseDataPORTUGAL.js';
import {
    Model200PrayerCalMethodsResponseDataPORTUGALFromJSON,
    Model200PrayerCalMethodsResponseDataPORTUGALFromJSONTyped,
    Model200PrayerCalMethodsResponseDataPORTUGALToJSON,
    Model200PrayerCalMethodsResponseDataPORTUGALToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataPORTUGAL.js';
import type { Model200TimesResponseDataMetaMethod } from './Model200TimesResponseDataMetaMethod.js';
import {
    Model200TimesResponseDataMetaMethodFromJSON,
    Model200TimesResponseDataMetaMethodFromJSONTyped,
    Model200TimesResponseDataMetaMethodToJSON,
    Model200TimesResponseDataMetaMethodToJSONTyped,
} from './Model200TimesResponseDataMetaMethod.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseData
 */
export interface Model200PrayerCalMethodsResponseData {
    /**
     * 
     * @type {Model200TimesResponseDataMetaMethod}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    mWL?: Model200TimesResponseDataMetaMethod;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataISNA}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    iSNA?: Model200PrayerCalMethodsResponseDataISNA;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataEGYPT}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    eGYPT?: Model200PrayerCalMethodsResponseDataEGYPT;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMAKKAH}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    mAKKAH?: Model200PrayerCalMethodsResponseDataMAKKAH;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKARACHI}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    kARACHI?: Model200PrayerCalMethodsResponseDataKARACHI;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTEHRAN}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    tEHRAN?: Model200PrayerCalMethodsResponseDataTEHRAN;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJAFARI}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    jAFARI?: Model200PrayerCalMethodsResponseDataJAFARI;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataGULF}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    gULF?: Model200PrayerCalMethodsResponseDataGULF;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKUWAIT}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    kUWAIT?: Model200PrayerCalMethodsResponseDataKUWAIT;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataQATAR}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    qATAR?: Model200PrayerCalMethodsResponseDataQATAR;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataSINGAPORE}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    sINGAPORE?: Model200PrayerCalMethodsResponseDataSINGAPORE;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataFRANCE}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    fRANCE?: Model200PrayerCalMethodsResponseDataFRANCE;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTURKEY}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    tURKEY?: Model200PrayerCalMethodsResponseDataTURKEY;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataRUSSIA}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    rUSSIA?: Model200PrayerCalMethodsResponseDataRUSSIA;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMOONSIGHTING}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    mOONSIGHTING?: Model200PrayerCalMethodsResponseDataMOONSIGHTING;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataDUBAI}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    dUBAI?: Model200PrayerCalMethodsResponseDataDUBAI;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJAKIM}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    jAKIM?: Model200PrayerCalMethodsResponseDataJAKIM;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTUNISIA}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    tUNISIA?: Model200PrayerCalMethodsResponseDataTUNISIA;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataALGERIA}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    aLGERIA?: Model200PrayerCalMethodsResponseDataALGERIA;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKEMENAG}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    kEMENAG?: Model200PrayerCalMethodsResponseDataKEMENAG;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMOROCCO}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    mOROCCO?: Model200PrayerCalMethodsResponseDataMOROCCO;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataPORTUGAL}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    pORTUGAL?: Model200PrayerCalMethodsResponseDataPORTUGAL;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJORDAN}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    jORDAN?: Model200PrayerCalMethodsResponseDataJORDAN;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataCUSTOM}
     * @memberof Model200PrayerCalMethodsResponseData
     */
    cUSTOM?: Model200PrayerCalMethodsResponseDataCUSTOM;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseData interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseData(value: object): value is Model200PrayerCalMethodsResponseData {
    return true;
}

export function Model200PrayerCalMethodsResponseDataFromJSON(json: any): Model200PrayerCalMethodsResponseData {
    return Model200PrayerCalMethodsResponseDataFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'mWL': json['MWL'] == null ? undefined : Model200TimesResponseDataMetaMethodFromJSON(json['MWL']),
        'iSNA': json['ISNA'] == null ? undefined : Model200PrayerCalMethodsResponseDataISNAFromJSON(json['ISNA']),
        'eGYPT': json['EGYPT'] == null ? undefined : Model200PrayerCalMethodsResponseDataEGYPTFromJSON(json['EGYPT']),
        'mAKKAH': json['MAKKAH'] == null ? undefined : Model200PrayerCalMethodsResponseDataMAKKAHFromJSON(json['MAKKAH']),
        'kARACHI': json['KARACHI'] == null ? undefined : Model200PrayerCalMethodsResponseDataKARACHIFromJSON(json['KARACHI']),
        'tEHRAN': json['TEHRAN'] == null ? undefined : Model200PrayerCalMethodsResponseDataTEHRANFromJSON(json['TEHRAN']),
        'jAFARI': json['JAFARI'] == null ? undefined : Model200PrayerCalMethodsResponseDataJAFARIFromJSON(json['JAFARI']),
        'gULF': json['GULF'] == null ? undefined : Model200PrayerCalMethodsResponseDataGULFFromJSON(json['GULF']),
        'kUWAIT': json['KUWAIT'] == null ? undefined : Model200PrayerCalMethodsResponseDataKUWAITFromJSON(json['KUWAIT']),
        'qATAR': json['QATAR'] == null ? undefined : Model200PrayerCalMethodsResponseDataQATARFromJSON(json['QATAR']),
        'sINGAPORE': json['SINGAPORE'] == null ? undefined : Model200PrayerCalMethodsResponseDataSINGAPOREFromJSON(json['SINGAPORE']),
        'fRANCE': json['FRANCE'] == null ? undefined : Model200PrayerCalMethodsResponseDataFRANCEFromJSON(json['FRANCE']),
        'tURKEY': json['TURKEY'] == null ? undefined : Model200PrayerCalMethodsResponseDataTURKEYFromJSON(json['TURKEY']),
        'rUSSIA': json['RUSSIA'] == null ? undefined : Model200PrayerCalMethodsResponseDataRUSSIAFromJSON(json['RUSSIA']),
        'mOONSIGHTING': json['MOONSIGHTING'] == null ? undefined : Model200PrayerCalMethodsResponseDataMOONSIGHTINGFromJSON(json['MOONSIGHTING']),
        'dUBAI': json['DUBAI'] == null ? undefined : Model200PrayerCalMethodsResponseDataDUBAIFromJSON(json['DUBAI']),
        'jAKIM': json['JAKIM'] == null ? undefined : Model200PrayerCalMethodsResponseDataJAKIMFromJSON(json['JAKIM']),
        'tUNISIA': json['TUNISIA'] == null ? undefined : Model200PrayerCalMethodsResponseDataTUNISIAFromJSON(json['TUNISIA']),
        'aLGERIA': json['ALGERIA'] == null ? undefined : Model200PrayerCalMethodsResponseDataALGERIAFromJSON(json['ALGERIA']),
        'kEMENAG': json['KEMENAG'] == null ? undefined : Model200PrayerCalMethodsResponseDataKEMENAGFromJSON(json['KEMENAG']),
        'mOROCCO': json['MOROCCO'] == null ? undefined : Model200PrayerCalMethodsResponseDataMOROCCOFromJSON(json['MOROCCO']),
        'pORTUGAL': json['PORTUGAL'] == null ? undefined : Model200PrayerCalMethodsResponseDataPORTUGALFromJSON(json['PORTUGAL']),
        'jORDAN': json['JORDAN'] == null ? undefined : Model200PrayerCalMethodsResponseDataJORDANFromJSON(json['JORDAN']),
        'cUSTOM': json['CUSTOM'] == null ? undefined : Model200PrayerCalMethodsResponseDataCUSTOMFromJSON(json['CUSTOM']),
    };
}

export function Model200PrayerCalMethodsResponseDataToJSON(json: any): Model200PrayerCalMethodsResponseData {
    return Model200PrayerCalMethodsResponseDataToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataToJSONTyped(value?: Model200PrayerCalMethodsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'MWL': Model200TimesResponseDataMetaMethodToJSON(value['mWL']),
        'ISNA': Model200PrayerCalMethodsResponseDataISNAToJSON(value['iSNA']),
        'EGYPT': Model200PrayerCalMethodsResponseDataEGYPTToJSON(value['eGYPT']),
        'MAKKAH': Model200PrayerCalMethodsResponseDataMAKKAHToJSON(value['mAKKAH']),
        'KARACHI': Model200PrayerCalMethodsResponseDataKARACHIToJSON(value['kARACHI']),
        'TEHRAN': Model200PrayerCalMethodsResponseDataTEHRANToJSON(value['tEHRAN']),
        'JAFARI': Model200PrayerCalMethodsResponseDataJAFARIToJSON(value['jAFARI']),
        'GULF': Model200PrayerCalMethodsResponseDataGULFToJSON(value['gULF']),
        'KUWAIT': Model200PrayerCalMethodsResponseDataKUWAITToJSON(value['kUWAIT']),
        'QATAR': Model200PrayerCalMethodsResponseDataQATARToJSON(value['qATAR']),
        'SINGAPORE': Model200PrayerCalMethodsResponseDataSINGAPOREToJSON(value['sINGAPORE']),
        'FRANCE': Model200PrayerCalMethodsResponseDataFRANCEToJSON(value['fRANCE']),
        'TURKEY': Model200PrayerCalMethodsResponseDataTURKEYToJSON(value['tURKEY']),
        'RUSSIA': Model200PrayerCalMethodsResponseDataRUSSIAToJSON(value['rUSSIA']),
        'MOONSIGHTING': Model200PrayerCalMethodsResponseDataMOONSIGHTINGToJSON(value['mOONSIGHTING']),
        'DUBAI': Model200PrayerCalMethodsResponseDataDUBAIToJSON(value['dUBAI']),
        'JAKIM': Model200PrayerCalMethodsResponseDataJAKIMToJSON(value['jAKIM']),
        'TUNISIA': Model200PrayerCalMethodsResponseDataTUNISIAToJSON(value['tUNISIA']),
        'ALGERIA': Model200PrayerCalMethodsResponseDataALGERIAToJSON(value['aLGERIA']),
        'KEMENAG': Model200PrayerCalMethodsResponseDataKEMENAGToJSON(value['kEMENAG']),
        'MOROCCO': Model200PrayerCalMethodsResponseDataMOROCCOToJSON(value['mOROCCO']),
        'PORTUGAL': Model200PrayerCalMethodsResponseDataPORTUGALToJSON(value['pORTUGAL']),
        'JORDAN': Model200PrayerCalMethodsResponseDataJORDANToJSON(value['jORDAN']),
        'CUSTOM': Model200PrayerCalMethodsResponseDataCUSTOMToJSON(value['cUSTOM']),
    };
}

