/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataMAKKAHParams } from './Model200PrayerCalMethodsResponseDataMAKKAHParams.js';
import {
    Model200PrayerCalMethodsResponseDataMAKKAHParamsFromJSON,
    Model200PrayerCalMethodsResponseDataMAKKAHParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMAKKAHParamsToJSON,
    Model200PrayerCalMethodsResponseDataMAKKAHParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMAKKAHParams.js';
import type { Model200PrayerCalMethodsResponseDataMAKKAHLocation } from './Model200PrayerCalMethodsResponseDataMAKKAHLocation.js';
import {
    Model200PrayerCalMethodsResponseDataMAKKAHLocationFromJSON,
    Model200PrayerCalMethodsResponseDataMAKKAHLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataMAKKAHLocationToJSON,
    Model200PrayerCalMethodsResponseDataMAKKAHLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataMAKKAHLocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataMAKKAH
 */
export interface Model200PrayerCalMethodsResponseDataMAKKAH {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataMAKKAH
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataMAKKAH
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMAKKAHParams}
     * @memberof Model200PrayerCalMethodsResponseDataMAKKAH
     */
    params?: Model200PrayerCalMethodsResponseDataMAKKAHParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataMAKKAHLocation}
     * @memberof Model200PrayerCalMethodsResponseDataMAKKAH
     */
    location?: Model200PrayerCalMethodsResponseDataMAKKAHLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataMAKKAH interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataMAKKAH(value: object): value is Model200PrayerCalMethodsResponseDataMAKKAH {
    return true;
}

export function Model200PrayerCalMethodsResponseDataMAKKAHFromJSON(json: any): Model200PrayerCalMethodsResponseDataMAKKAH {
    return Model200PrayerCalMethodsResponseDataMAKKAHFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMAKKAHFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataMAKKAH {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataMAKKAHParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataMAKKAHLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataMAKKAHToJSON(json: any): Model200PrayerCalMethodsResponseDataMAKKAH {
    return Model200PrayerCalMethodsResponseDataMAKKAHToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataMAKKAHToJSONTyped(value?: Model200PrayerCalMethodsResponseDataMAKKAH | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataMAKKAHParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataMAKKAHLocationToJSON(value['location']),
    };
}

