/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataJORDANParams
 */
export interface Model200PrayerCalMethodsResponseDataJORDANParams {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJORDANParams
     */
    fajr?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataJORDANParams
     */
    maghrib?: string;
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJORDANParams
     */
    isha?: number;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataJORDANParams interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataJORDANParams(value: object): value is Model200PrayerCalMethodsResponseDataJORDANParams {
    return true;
}

export function Model200PrayerCalMethodsResponseDataJORDANParamsFromJSON(json: any): Model200PrayerCalMethodsResponseDataJORDANParams {
    return Model200PrayerCalMethodsResponseDataJORDANParamsFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJORDANParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataJORDANParams {
    if (json == null) {
        return json;
    }
    return {
        
        'fajr': json['Fajr'] == null ? undefined : json['Fajr'],
        'maghrib': json['Maghrib'] == null ? undefined : json['Maghrib'],
        'isha': json['Isha'] == null ? undefined : json['Isha'],
    };
}

export function Model200PrayerCalMethodsResponseDataJORDANParamsToJSON(json: any): Model200PrayerCalMethodsResponseDataJORDANParams {
    return Model200PrayerCalMethodsResponseDataJORDANParamsToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJORDANParamsToJSONTyped(value?: Model200PrayerCalMethodsResponseDataJORDANParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Fajr': value['fajr'],
        'Maghrib': value['maghrib'],
        'Isha': value['isha'],
    };
}

