/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesNextPrayerResponseData } from './Model200TimesNextPrayerResponseData.js';
import {
    Model200TimesNextPrayerResponseDataFromJSON,
    Model200TimesNextPrayerResponseDataFromJSONTyped,
    Model200TimesNextPrayerResponseDataToJSON,
    Model200TimesNextPrayerResponseDataToJSONTyped,
} from './Model200TimesNextPrayerResponseData.js';

/**
 * 
 * @export
 * @interface Model200TimesNextPrayerResponse
 */
export interface Model200TimesNextPrayerResponse {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesNextPrayerResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesNextPrayerResponse
     */
    status?: string;
    /**
     * 
     * @type {Model200TimesNextPrayerResponseData}
     * @memberof Model200TimesNextPrayerResponse
     */
    data?: Model200TimesNextPrayerResponseData;
}

/**
 * Check if a given object implements the Model200TimesNextPrayerResponse interface.
 */
export function instanceOfModel200TimesNextPrayerResponse(value: object): value is Model200TimesNextPrayerResponse {
    return true;
}

export function Model200TimesNextPrayerResponseFromJSON(json: any): Model200TimesNextPrayerResponse {
    return Model200TimesNextPrayerResponseFromJSONTyped(json, false);
}

export function Model200TimesNextPrayerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesNextPrayerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : Model200TimesNextPrayerResponseDataFromJSON(json['data']),
    };
}

export function Model200TimesNextPrayerResponseToJSON(json: any): Model200TimesNextPrayerResponse {
    return Model200TimesNextPrayerResponseToJSONTyped(json, false);
}

export function Model200TimesNextPrayerResponseToJSONTyped(value?: Model200TimesNextPrayerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': Model200TimesNextPrayerResponseDataToJSON(value['data']),
    };
}

