/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseData } from './Model200TimesResponseData.js';
import {
    Model200TimesResponseDataFromJSON,
    Model200TimesResponseDataFromJSONTyped,
    Model200TimesResponseDataToJSON,
    Model200TimesResponseDataToJSONTyped,
} from './Model200TimesResponseData.js';

/**
 * 
 * @export
 * @interface Model200TimesResponse
 */
export interface Model200TimesResponse {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponse
     */
    status?: string;
    /**
     * 
     * @type {Model200TimesResponseData}
     * @memberof Model200TimesResponse
     */
    data?: Model200TimesResponseData;
}

/**
 * Check if a given object implements the Model200TimesResponse interface.
 */
export function instanceOfModel200TimesResponse(value: object): value is Model200TimesResponse {
    return true;
}

export function Model200TimesResponseFromJSON(json: any): Model200TimesResponse {
    return Model200TimesResponseFromJSONTyped(json, false);
}

export function Model200TimesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : Model200TimesResponseDataFromJSON(json['data']),
    };
}

export function Model200TimesResponseToJSON(json: any): Model200TimesResponse {
    return Model200TimesResponseToJSONTyped(json, false);
}

export function Model200TimesResponseToJSONTyped(value?: Model200TimesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': Model200TimesResponseDataToJSON(value['data']),
    };
}

