/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataJAFARIParams } from './Model200PrayerCalMethodsResponseDataJAFARIParams.js';
import {
    Model200PrayerCalMethodsResponseDataJAFARIParamsFromJSON,
    Model200PrayerCalMethodsResponseDataJAFARIParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJAFARIParamsToJSON,
    Model200PrayerCalMethodsResponseDataJAFARIParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJAFARIParams.js';
import type { Model200PrayerCalMethodsResponseDataJAFARILocation } from './Model200PrayerCalMethodsResponseDataJAFARILocation.js';
import {
    Model200PrayerCalMethodsResponseDataJAFARILocationFromJSON,
    Model200PrayerCalMethodsResponseDataJAFARILocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJAFARILocationToJSON,
    Model200PrayerCalMethodsResponseDataJAFARILocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJAFARILocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataJAFARI
 */
export interface Model200PrayerCalMethodsResponseDataJAFARI {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARI
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARI
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJAFARIParams}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARI
     */
    params?: Model200PrayerCalMethodsResponseDataJAFARIParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJAFARILocation}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARI
     */
    location?: Model200PrayerCalMethodsResponseDataJAFARILocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataJAFARI interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataJAFARI(value: object): value is Model200PrayerCalMethodsResponseDataJAFARI {
    return true;
}

export function Model200PrayerCalMethodsResponseDataJAFARIFromJSON(json: any): Model200PrayerCalMethodsResponseDataJAFARI {
    return Model200PrayerCalMethodsResponseDataJAFARIFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJAFARIFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataJAFARI {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataJAFARIParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataJAFARILocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataJAFARIToJSON(json: any): Model200PrayerCalMethodsResponseDataJAFARI {
    return Model200PrayerCalMethodsResponseDataJAFARIToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJAFARIToJSONTyped(value?: Model200PrayerCalMethodsResponseDataJAFARI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataJAFARIParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataJAFARILocationToJSON(value['location']),
    };
}

