/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataKEMENAGLocation } from './Model200PrayerCalMethodsResponseDataKEMENAGLocation.js';
import {
    Model200PrayerCalMethodsResponseDataKEMENAGLocationFromJSON,
    Model200PrayerCalMethodsResponseDataKEMENAGLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKEMENAGLocationToJSON,
    Model200PrayerCalMethodsResponseDataKEMENAGLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKEMENAGLocation.js';
import type { Model200PrayerCalMethodsResponseDataSINGAPOREParams } from './Model200PrayerCalMethodsResponseDataSINGAPOREParams.js';
import {
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataSINGAPOREParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataKEMENAG
 */
export interface Model200PrayerCalMethodsResponseDataKEMENAG {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataKEMENAG
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataKEMENAG
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataSINGAPOREParams}
     * @memberof Model200PrayerCalMethodsResponseDataKEMENAG
     */
    params?: Model200PrayerCalMethodsResponseDataSINGAPOREParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKEMENAGLocation}
     * @memberof Model200PrayerCalMethodsResponseDataKEMENAG
     */
    location?: Model200PrayerCalMethodsResponseDataKEMENAGLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataKEMENAG interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataKEMENAG(value: object): value is Model200PrayerCalMethodsResponseDataKEMENAG {
    return true;
}

export function Model200PrayerCalMethodsResponseDataKEMENAGFromJSON(json: any): Model200PrayerCalMethodsResponseDataKEMENAG {
    return Model200PrayerCalMethodsResponseDataKEMENAGFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataKEMENAGFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataKEMENAG {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataKEMENAGLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataKEMENAGToJSON(json: any): Model200PrayerCalMethodsResponseDataKEMENAG {
    return Model200PrayerCalMethodsResponseDataKEMENAGToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataKEMENAGToJSONTyped(value?: Model200PrayerCalMethodsResponseDataKEMENAG | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataKEMENAGLocationToJSON(value['location']),
    };
}

