/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200CalendarTimesResponseDataTimings
 */
export interface Model200CalendarTimesResponseDataTimings {
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    fajr?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    sunrise?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    dhuhr?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    asr?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    sunset?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    maghrib?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    isha?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    imsak?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    midnight?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    firstthird?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponseDataTimings
     */
    lastthird?: string;
}

/**
 * Check if a given object implements the Model200CalendarTimesResponseDataTimings interface.
 */
export function instanceOfModel200CalendarTimesResponseDataTimings(value: object): value is Model200CalendarTimesResponseDataTimings {
    return true;
}

export function Model200CalendarTimesResponseDataTimingsFromJSON(json: any): Model200CalendarTimesResponseDataTimings {
    return Model200CalendarTimesResponseDataTimingsFromJSONTyped(json, false);
}

export function Model200CalendarTimesResponseDataTimingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200CalendarTimesResponseDataTimings {
    if (json == null) {
        return json;
    }
    return {
        
        'fajr': json['Fajr'] == null ? undefined : json['Fajr'],
        'sunrise': json['Sunrise'] == null ? undefined : json['Sunrise'],
        'dhuhr': json['Dhuhr'] == null ? undefined : json['Dhuhr'],
        'asr': json['Asr'] == null ? undefined : json['Asr'],
        'sunset': json['Sunset'] == null ? undefined : json['Sunset'],
        'maghrib': json['Maghrib'] == null ? undefined : json['Maghrib'],
        'isha': json['Isha'] == null ? undefined : json['Isha'],
        'imsak': json['Imsak'] == null ? undefined : json['Imsak'],
        'midnight': json['Midnight'] == null ? undefined : json['Midnight'],
        'firstthird': json['Firstthird'] == null ? undefined : json['Firstthird'],
        'lastthird': json['Lastthird'] == null ? undefined : json['Lastthird'],
    };
}

export function Model200CalendarTimesResponseDataTimingsToJSON(json: any): Model200CalendarTimesResponseDataTimings {
    return Model200CalendarTimesResponseDataTimingsToJSONTyped(json, false);
}

export function Model200CalendarTimesResponseDataTimingsToJSONTyped(value?: Model200CalendarTimesResponseDataTimings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Fajr': value['fajr'],
        'Sunrise': value['sunrise'],
        'Dhuhr': value['dhuhr'],
        'Asr': value['asr'],
        'Sunset': value['sunset'],
        'Maghrib': value['maghrib'],
        'Isha': value['isha'],
        'Imsak': value['imsak'],
        'Midnight': value['midnight'],
        'Firstthird': value['firstthird'],
        'Lastthird': value['lastthird'],
    };
}

