/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataMetaOffset } from './Model200TimesResponseDataMetaOffset.js';
import {
    Model200TimesResponseDataMetaOffsetFromJSON,
    Model200TimesResponseDataMetaOffsetFromJSONTyped,
    Model200TimesResponseDataMetaOffsetToJSON,
    Model200TimesResponseDataMetaOffsetToJSONTyped,
} from './Model200TimesResponseDataMetaOffset.js';
import type { Model200TimesResponseDataMetaMethod } from './Model200TimesResponseDataMetaMethod.js';
import {
    Model200TimesResponseDataMetaMethodFromJSON,
    Model200TimesResponseDataMetaMethodFromJSONTyped,
    Model200TimesResponseDataMetaMethodToJSON,
    Model200TimesResponseDataMetaMethodToJSONTyped,
} from './Model200TimesResponseDataMetaMethod.js';

/**
 * 
 * @export
 * @interface Model200TimesResponseDataMeta
 */
export interface Model200TimesResponseDataMeta {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMeta
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMeta
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataMeta
     */
    timezone?: string;
    /**
     * 
     * @type {Model200TimesResponseDataMetaMethod}
     * @memberof Model200TimesResponseDataMeta
     */
    method?: Model200TimesResponseDataMetaMethod;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataMeta
     */
    latitudeAdjustmentMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataMeta
     */
    midnightMode?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataMeta
     */
    school?: string;
    /**
     * 
     * @type {Model200TimesResponseDataMetaOffset}
     * @memberof Model200TimesResponseDataMeta
     */
    offset?: Model200TimesResponseDataMetaOffset;
}

/**
 * Check if a given object implements the Model200TimesResponseDataMeta interface.
 */
export function instanceOfModel200TimesResponseDataMeta(value: object): value is Model200TimesResponseDataMeta {
    return true;
}

export function Model200TimesResponseDataMetaFromJSON(json: any): Model200TimesResponseDataMeta {
    return Model200TimesResponseDataMetaFromJSONTyped(json, false);
}

export function Model200TimesResponseDataMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'method': json['method'] == null ? undefined : Model200TimesResponseDataMetaMethodFromJSON(json['method']),
        'latitudeAdjustmentMethod': json['latitudeAdjustmentMethod'] == null ? undefined : json['latitudeAdjustmentMethod'],
        'midnightMode': json['midnightMode'] == null ? undefined : json['midnightMode'],
        'school': json['school'] == null ? undefined : json['school'],
        'offset': json['offset'] == null ? undefined : Model200TimesResponseDataMetaOffsetFromJSON(json['offset']),
    };
}

export function Model200TimesResponseDataMetaToJSON(json: any): Model200TimesResponseDataMeta {
    return Model200TimesResponseDataMetaToJSONTyped(json, false);
}

export function Model200TimesResponseDataMetaToJSONTyped(value?: Model200TimesResponseDataMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'timezone': value['timezone'],
        'method': Model200TimesResponseDataMetaMethodToJSON(value['method']),
        'latitudeAdjustmentMethod': value['latitudeAdjustmentMethod'],
        'midnightMode': value['midnightMode'],
        'school': value['school'],
        'offset': Model200TimesResponseDataMetaOffsetToJSON(value['offset']),
    };
}

