/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataGULFParams } from './Model200PrayerCalMethodsResponseDataGULFParams.js';
import {
    Model200PrayerCalMethodsResponseDataGULFParamsFromJSON,
    Model200PrayerCalMethodsResponseDataGULFParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataGULFParamsToJSON,
    Model200PrayerCalMethodsResponseDataGULFParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataGULFParams.js';
import type { Model200PrayerCalMethodsResponseDataGULFLocation } from './Model200PrayerCalMethodsResponseDataGULFLocation.js';
import {
    Model200PrayerCalMethodsResponseDataGULFLocationFromJSON,
    Model200PrayerCalMethodsResponseDataGULFLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataGULFLocationToJSON,
    Model200PrayerCalMethodsResponseDataGULFLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataGULFLocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataGULF
 */
export interface Model200PrayerCalMethodsResponseDataGULF {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataGULF
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataGULF
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataGULFParams}
     * @memberof Model200PrayerCalMethodsResponseDataGULF
     */
    params?: Model200PrayerCalMethodsResponseDataGULFParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataGULFLocation}
     * @memberof Model200PrayerCalMethodsResponseDataGULF
     */
    location?: Model200PrayerCalMethodsResponseDataGULFLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataGULF interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataGULF(value: object): value is Model200PrayerCalMethodsResponseDataGULF {
    return true;
}

export function Model200PrayerCalMethodsResponseDataGULFFromJSON(json: any): Model200PrayerCalMethodsResponseDataGULF {
    return Model200PrayerCalMethodsResponseDataGULFFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataGULFFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataGULF {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataGULFParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataGULFLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataGULFToJSON(json: any): Model200PrayerCalMethodsResponseDataGULF {
    return Model200PrayerCalMethodsResponseDataGULFToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataGULFToJSONTyped(value?: Model200PrayerCalMethodsResponseDataGULF | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataGULFParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataGULFLocationToJSON(value['location']),
    };
}

