/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataDateHijriWeekday } from './Model200TimesResponseDataDateHijriWeekday.js';
import {
    Model200TimesResponseDataDateHijriWeekdayFromJSON,
    Model200TimesResponseDataDateHijriWeekdayFromJSONTyped,
    Model200TimesResponseDataDateHijriWeekdayToJSON,
    Model200TimesResponseDataDateHijriWeekdayToJSONTyped,
} from './Model200TimesResponseDataDateHijriWeekday.js';
import type { Model200TimesResponseDataDateHijriDesignation } from './Model200TimesResponseDataDateHijriDesignation.js';
import {
    Model200TimesResponseDataDateHijriDesignationFromJSON,
    Model200TimesResponseDataDateHijriDesignationFromJSONTyped,
    Model200TimesResponseDataDateHijriDesignationToJSON,
    Model200TimesResponseDataDateHijriDesignationToJSONTyped,
} from './Model200TimesResponseDataDateHijriDesignation.js';
import type { Model200TimesResponseDataDateHijriMonth } from './Model200TimesResponseDataDateHijriMonth.js';
import {
    Model200TimesResponseDataDateHijriMonthFromJSON,
    Model200TimesResponseDataDateHijriMonthFromJSONTyped,
    Model200TimesResponseDataDateHijriMonthToJSON,
    Model200TimesResponseDataDateHijriMonthToJSONTyped,
} from './Model200TimesResponseDataDateHijriMonth.js';

/**
 * 
 * @export
 * @interface Model200TimesResponseDataDateHijri
 */
export interface Model200TimesResponseDataDateHijri {
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijri
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijri
     */
    format?: string;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijri
     */
    day?: string;
    /**
     * 
     * @type {Model200TimesResponseDataDateHijriWeekday}
     * @memberof Model200TimesResponseDataDateHijri
     */
    weekday?: Model200TimesResponseDataDateHijriWeekday;
    /**
     * 
     * @type {Model200TimesResponseDataDateHijriMonth}
     * @memberof Model200TimesResponseDataDateHijri
     */
    month?: Model200TimesResponseDataDateHijriMonth;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijri
     */
    year?: string;
    /**
     * 
     * @type {Model200TimesResponseDataDateHijriDesignation}
     * @memberof Model200TimesResponseDataDateHijri
     */
    designation?: Model200TimesResponseDataDateHijriDesignation;
    /**
     * 
     * @type {Array<any>}
     * @memberof Model200TimesResponseDataDateHijri
     */
    holidays?: Array<any>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model200TimesResponseDataDateHijri
     */
    adjustedHolidays?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataDateHijri
     */
    method?: string;
}

/**
 * Check if a given object implements the Model200TimesResponseDataDateHijri interface.
 */
export function instanceOfModel200TimesResponseDataDateHijri(value: object): value is Model200TimesResponseDataDateHijri {
    return true;
}

export function Model200TimesResponseDataDateHijriFromJSON(json: any): Model200TimesResponseDataDateHijri {
    return Model200TimesResponseDataDateHijriFromJSONTyped(json, false);
}

export function Model200TimesResponseDataDateHijriFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataDateHijri {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'format': json['format'] == null ? undefined : json['format'],
        'day': json['day'] == null ? undefined : json['day'],
        'weekday': json['weekday'] == null ? undefined : Model200TimesResponseDataDateHijriWeekdayFromJSON(json['weekday']),
        'month': json['month'] == null ? undefined : Model200TimesResponseDataDateHijriMonthFromJSON(json['month']),
        'year': json['year'] == null ? undefined : json['year'],
        'designation': json['designation'] == null ? undefined : Model200TimesResponseDataDateHijriDesignationFromJSON(json['designation']),
        'holidays': json['holidays'] == null ? undefined : json['holidays'],
        'adjustedHolidays': json['adjustedHolidays'] == null ? undefined : json['adjustedHolidays'],
        'method': json['method'] == null ? undefined : json['method'],
    };
}

export function Model200TimesResponseDataDateHijriToJSON(json: any): Model200TimesResponseDataDateHijri {
    return Model200TimesResponseDataDateHijriToJSONTyped(json, false);
}

export function Model200TimesResponseDataDateHijriToJSONTyped(value?: Model200TimesResponseDataDateHijri | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'format': value['format'],
        'day': value['day'],
        'weekday': Model200TimesResponseDataDateHijriWeekdayToJSON(value['weekday']),
        'month': Model200TimesResponseDataDateHijriMonthToJSON(value['month']),
        'year': value['year'],
        'designation': Model200TimesResponseDataDateHijriDesignationToJSON(value['designation']),
        'holidays': value['holidays'],
        'adjustedHolidays': value['adjustedHolidays'],
        'method': value['method'],
    };
}

