/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Meta } from './Meta.js';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta.js';
import type { Model200TimesNextPrayerResponseDataTimings } from './Model200TimesNextPrayerResponseDataTimings.js';
import {
    Model200TimesNextPrayerResponseDataTimingsFromJSON,
    Model200TimesNextPrayerResponseDataTimingsFromJSONTyped,
    Model200TimesNextPrayerResponseDataTimingsToJSON,
    Model200TimesNextPrayerResponseDataTimingsToJSONTyped,
} from './Model200TimesNextPrayerResponseDataTimings.js';

/**
 * 
 * @export
 * @interface Model200TimesNextPrayerResponseData
 */
export interface Model200TimesNextPrayerResponseData {
    /**
     * 
     * @type {Model200TimesNextPrayerResponseDataTimings}
     * @memberof Model200TimesNextPrayerResponseData
     */
    timings?: Model200TimesNextPrayerResponseDataTimings;
    /**
     * 
     * @type {Date}
     * @memberof Model200TimesNextPrayerResponseData
     */
    date?: Date;
    /**
     * 
     * @type {Meta}
     * @memberof Model200TimesNextPrayerResponseData
     */
    meta?: Meta;
}

/**
 * Check if a given object implements the Model200TimesNextPrayerResponseData interface.
 */
export function instanceOfModel200TimesNextPrayerResponseData(value: object): value is Model200TimesNextPrayerResponseData {
    return true;
}

export function Model200TimesNextPrayerResponseDataFromJSON(json: any): Model200TimesNextPrayerResponseData {
    return Model200TimesNextPrayerResponseDataFromJSONTyped(json, false);
}

export function Model200TimesNextPrayerResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesNextPrayerResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'timings': json['timings'] == null ? undefined : Model200TimesNextPrayerResponseDataTimingsFromJSON(json['timings']),
        'date': json['date'] == null ? undefined : json['date'],
        'meta': json['meta'] == null ? undefined : MetaFromJSON(json['meta']),
    };
}

export function Model200TimesNextPrayerResponseDataToJSON(json: any): Model200TimesNextPrayerResponseData {
    return Model200TimesNextPrayerResponseDataToJSONTyped(json, false);
}

export function Model200TimesNextPrayerResponseDataToJSONTyped(value?: Model200TimesNextPrayerResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timings': Model200TimesNextPrayerResponseDataTimingsToJSON(value['timings']),
        'date': value['date'],
        'meta': MetaToJSON(value['meta']),
    };
}

