/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataKUWAITParams } from './Model200PrayerCalMethodsResponseDataKUWAITParams.js';
import {
    Model200PrayerCalMethodsResponseDataKUWAITParamsFromJSON,
    Model200PrayerCalMethodsResponseDataKUWAITParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKUWAITParamsToJSON,
    Model200PrayerCalMethodsResponseDataKUWAITParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKUWAITParams.js';
import type { Model200PrayerCalMethodsResponseDataKUWAITLocation } from './Model200PrayerCalMethodsResponseDataKUWAITLocation.js';
import {
    Model200PrayerCalMethodsResponseDataKUWAITLocationFromJSON,
    Model200PrayerCalMethodsResponseDataKUWAITLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKUWAITLocationToJSON,
    Model200PrayerCalMethodsResponseDataKUWAITLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKUWAITLocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataKUWAIT
 */
export interface Model200PrayerCalMethodsResponseDataKUWAIT {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataKUWAIT
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataKUWAIT
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKUWAITParams}
     * @memberof Model200PrayerCalMethodsResponseDataKUWAIT
     */
    params?: Model200PrayerCalMethodsResponseDataKUWAITParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKUWAITLocation}
     * @memberof Model200PrayerCalMethodsResponseDataKUWAIT
     */
    location?: Model200PrayerCalMethodsResponseDataKUWAITLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataKUWAIT interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataKUWAIT(value: object): value is Model200PrayerCalMethodsResponseDataKUWAIT {
    return true;
}

export function Model200PrayerCalMethodsResponseDataKUWAITFromJSON(json: any): Model200PrayerCalMethodsResponseDataKUWAIT {
    return Model200PrayerCalMethodsResponseDataKUWAITFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataKUWAITFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataKUWAIT {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataKUWAITParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataKUWAITLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataKUWAITToJSON(json: any): Model200PrayerCalMethodsResponseDataKUWAIT {
    return Model200PrayerCalMethodsResponseDataKUWAITToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataKUWAITToJSONTyped(value?: Model200PrayerCalMethodsResponseDataKUWAIT | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataKUWAITParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataKUWAITLocationToJSON(value['location']),
    };
}

