/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataJAKIMLocation } from './Model200PrayerCalMethodsResponseDataJAKIMLocation.js';
import {
    Model200PrayerCalMethodsResponseDataJAKIMLocationFromJSON,
    Model200PrayerCalMethodsResponseDataJAKIMLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJAKIMLocationToJSON,
    Model200PrayerCalMethodsResponseDataJAKIMLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJAKIMLocation.js';
import type { Model200PrayerCalMethodsResponseDataSINGAPOREParams } from './Model200PrayerCalMethodsResponseDataSINGAPOREParams.js';
import {
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataSINGAPOREParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataJAKIM
 */
export interface Model200PrayerCalMethodsResponseDataJAKIM {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJAKIM
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataJAKIM
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataSINGAPOREParams}
     * @memberof Model200PrayerCalMethodsResponseDataJAKIM
     */
    params?: Model200PrayerCalMethodsResponseDataSINGAPOREParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJAKIMLocation}
     * @memberof Model200PrayerCalMethodsResponseDataJAKIM
     */
    location?: Model200PrayerCalMethodsResponseDataJAKIMLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataJAKIM interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataJAKIM(value: object): value is Model200PrayerCalMethodsResponseDataJAKIM {
    return true;
}

export function Model200PrayerCalMethodsResponseDataJAKIMFromJSON(json: any): Model200PrayerCalMethodsResponseDataJAKIM {
    return Model200PrayerCalMethodsResponseDataJAKIMFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJAKIMFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataJAKIM {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataJAKIMLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataJAKIMToJSON(json: any): Model200PrayerCalMethodsResponseDataJAKIM {
    return Model200PrayerCalMethodsResponseDataJAKIMToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJAKIMToJSONTyped(value?: Model200PrayerCalMethodsResponseDataJAKIM | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataJAKIMLocationToJSON(value['location']),
    };
}

