/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataFRANCELocation } from './Model200PrayerCalMethodsResponseDataFRANCELocation.js';
import {
    Model200PrayerCalMethodsResponseDataFRANCELocationFromJSON,
    Model200PrayerCalMethodsResponseDataFRANCELocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataFRANCELocationToJSON,
    Model200PrayerCalMethodsResponseDataFRANCELocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataFRANCELocation.js';
import type { Model200PrayerCalMethodsResponseDataFRANCEParams } from './Model200PrayerCalMethodsResponseDataFRANCEParams.js';
import {
    Model200PrayerCalMethodsResponseDataFRANCEParamsFromJSON,
    Model200PrayerCalMethodsResponseDataFRANCEParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataFRANCEParamsToJSON,
    Model200PrayerCalMethodsResponseDataFRANCEParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataFRANCEParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataFRANCE
 */
export interface Model200PrayerCalMethodsResponseDataFRANCE {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataFRANCE
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataFRANCE
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataFRANCEParams}
     * @memberof Model200PrayerCalMethodsResponseDataFRANCE
     */
    params?: Model200PrayerCalMethodsResponseDataFRANCEParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataFRANCELocation}
     * @memberof Model200PrayerCalMethodsResponseDataFRANCE
     */
    location?: Model200PrayerCalMethodsResponseDataFRANCELocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataFRANCE interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataFRANCE(value: object): value is Model200PrayerCalMethodsResponseDataFRANCE {
    return true;
}

export function Model200PrayerCalMethodsResponseDataFRANCEFromJSON(json: any): Model200PrayerCalMethodsResponseDataFRANCE {
    return Model200PrayerCalMethodsResponseDataFRANCEFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataFRANCEFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataFRANCE {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataFRANCEParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataFRANCELocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataFRANCEToJSON(json: any): Model200PrayerCalMethodsResponseDataFRANCE {
    return Model200PrayerCalMethodsResponseDataFRANCEToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataFRANCEToJSONTyped(value?: Model200PrayerCalMethodsResponseDataFRANCE | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataFRANCEParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataFRANCELocationToJSON(value['location']),
    };
}

