/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataJAFARIParams
 */
export interface Model200PrayerCalMethodsResponseDataJAFARIParams {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARIParams
     */
    fajr?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARIParams
     */
    isha?: number;
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARIParams
     */
    maghrib?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataJAFARIParams
     */
    midnight?: string;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataJAFARIParams interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataJAFARIParams(value: object): value is Model200PrayerCalMethodsResponseDataJAFARIParams {
    return true;
}

export function Model200PrayerCalMethodsResponseDataJAFARIParamsFromJSON(json: any): Model200PrayerCalMethodsResponseDataJAFARIParams {
    return Model200PrayerCalMethodsResponseDataJAFARIParamsFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJAFARIParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataJAFARIParams {
    if (json == null) {
        return json;
    }
    return {
        
        'fajr': json['Fajr'] == null ? undefined : json['Fajr'],
        'isha': json['Isha'] == null ? undefined : json['Isha'],
        'maghrib': json['Maghrib'] == null ? undefined : json['Maghrib'],
        'midnight': json['Midnight'] == null ? undefined : json['Midnight'],
    };
}

export function Model200PrayerCalMethodsResponseDataJAFARIParamsToJSON(json: any): Model200PrayerCalMethodsResponseDataJAFARIParams {
    return Model200PrayerCalMethodsResponseDataJAFARIParamsToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJAFARIParamsToJSONTyped(value?: Model200PrayerCalMethodsResponseDataJAFARIParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Fajr': value['fajr'],
        'Isha': value['isha'],
        'Maghrib': value['maghrib'],
        'Midnight': value['midnight'],
    };
}

