/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200TimesResponseDataMetaMethodParams } from './Model200TimesResponseDataMetaMethodParams.js';
import {
    Model200TimesResponseDataMetaMethodParamsFromJSON,
    Model200TimesResponseDataMetaMethodParamsFromJSONTyped,
    Model200TimesResponseDataMetaMethodParamsToJSON,
    Model200TimesResponseDataMetaMethodParamsToJSONTyped,
} from './Model200TimesResponseDataMetaMethodParams.js';
import type { Model200TimesResponseDataMetaMethodLocation } from './Model200TimesResponseDataMetaMethodLocation.js';
import {
    Model200TimesResponseDataMetaMethodLocationFromJSON,
    Model200TimesResponseDataMetaMethodLocationFromJSONTyped,
    Model200TimesResponseDataMetaMethodLocationToJSON,
    Model200TimesResponseDataMetaMethodLocationToJSONTyped,
} from './Model200TimesResponseDataMetaMethodLocation.js';

/**
 * 
 * @export
 * @interface Model200TimesResponseDataMetaMethod
 */
export interface Model200TimesResponseDataMetaMethod {
    /**
     * 
     * @type {number}
     * @memberof Model200TimesResponseDataMetaMethod
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200TimesResponseDataMetaMethod
     */
    name?: string;
    /**
     * 
     * @type {Model200TimesResponseDataMetaMethodParams}
     * @memberof Model200TimesResponseDataMetaMethod
     */
    params?: Model200TimesResponseDataMetaMethodParams;
    /**
     * 
     * @type {Model200TimesResponseDataMetaMethodLocation}
     * @memberof Model200TimesResponseDataMetaMethod
     */
    location?: Model200TimesResponseDataMetaMethodLocation;
}

/**
 * Check if a given object implements the Model200TimesResponseDataMetaMethod interface.
 */
export function instanceOfModel200TimesResponseDataMetaMethod(value: object): value is Model200TimesResponseDataMetaMethod {
    return true;
}

export function Model200TimesResponseDataMetaMethodFromJSON(json: any): Model200TimesResponseDataMetaMethod {
    return Model200TimesResponseDataMetaMethodFromJSONTyped(json, false);
}

export function Model200TimesResponseDataMetaMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200TimesResponseDataMetaMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200TimesResponseDataMetaMethodParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200TimesResponseDataMetaMethodLocationFromJSON(json['location']),
    };
}

export function Model200TimesResponseDataMetaMethodToJSON(json: any): Model200TimesResponseDataMetaMethod {
    return Model200TimesResponseDataMetaMethodToJSONTyped(json, false);
}

export function Model200TimesResponseDataMetaMethodToJSONTyped(value?: Model200TimesResponseDataMetaMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200TimesResponseDataMetaMethodParamsToJSON(value['params']),
        'location': Model200TimesResponseDataMetaMethodLocationToJSON(value['location']),
    };
}

