/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataALGERIALocation } from './Model200PrayerCalMethodsResponseDataALGERIALocation.js';
import {
    Model200PrayerCalMethodsResponseDataALGERIALocationFromJSON,
    Model200PrayerCalMethodsResponseDataALGERIALocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataALGERIALocationToJSON,
    Model200PrayerCalMethodsResponseDataALGERIALocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataALGERIALocation.js';
import type { Model200TimesResponseDataMetaMethodParams } from './Model200TimesResponseDataMetaMethodParams.js';
import {
    Model200TimesResponseDataMetaMethodParamsFromJSON,
    Model200TimesResponseDataMetaMethodParamsFromJSONTyped,
    Model200TimesResponseDataMetaMethodParamsToJSON,
    Model200TimesResponseDataMetaMethodParamsToJSONTyped,
} from './Model200TimesResponseDataMetaMethodParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataALGERIA
 */
export interface Model200PrayerCalMethodsResponseDataALGERIA {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataALGERIA
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataALGERIA
     */
    name?: string;
    /**
     * 
     * @type {Model200TimesResponseDataMetaMethodParams}
     * @memberof Model200PrayerCalMethodsResponseDataALGERIA
     */
    params?: Model200TimesResponseDataMetaMethodParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataALGERIALocation}
     * @memberof Model200PrayerCalMethodsResponseDataALGERIA
     */
    location?: Model200PrayerCalMethodsResponseDataALGERIALocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataALGERIA interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataALGERIA(value: object): value is Model200PrayerCalMethodsResponseDataALGERIA {
    return true;
}

export function Model200PrayerCalMethodsResponseDataALGERIAFromJSON(json: any): Model200PrayerCalMethodsResponseDataALGERIA {
    return Model200PrayerCalMethodsResponseDataALGERIAFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataALGERIAFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataALGERIA {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200TimesResponseDataMetaMethodParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataALGERIALocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataALGERIAToJSON(json: any): Model200PrayerCalMethodsResponseDataALGERIA {
    return Model200PrayerCalMethodsResponseDataALGERIAToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataALGERIAToJSONTyped(value?: Model200PrayerCalMethodsResponseDataALGERIA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200TimesResponseDataMetaMethodParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataALGERIALocationToJSON(value['location']),
    };
}

