/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200CalendarTimesResponseDataTimings } from './Model200CalendarTimesResponseDataTimings.js';
import {
    Model200CalendarTimesResponseDataTimingsFromJSON,
    Model200CalendarTimesResponseDataTimingsFromJSONTyped,
    Model200CalendarTimesResponseDataTimingsToJSON,
    Model200CalendarTimesResponseDataTimingsToJSONTyped,
} from './Model200CalendarTimesResponseDataTimings.js';

/**
 * 
 * @export
 * @interface Model200CalendarTimesResponseData
 */
export interface Model200CalendarTimesResponseData {
    /**
     * 
     * @type {Model200CalendarTimesResponseDataTimings}
     * @memberof Model200CalendarTimesResponseData
     */
    timings?: Model200CalendarTimesResponseDataTimings;
}

/**
 * Check if a given object implements the Model200CalendarTimesResponseData interface.
 */
export function instanceOfModel200CalendarTimesResponseData(value: object): value is Model200CalendarTimesResponseData {
    return true;
}

export function Model200CalendarTimesResponseDataFromJSON(json: any): Model200CalendarTimesResponseData {
    return Model200CalendarTimesResponseDataFromJSONTyped(json, false);
}

export function Model200CalendarTimesResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200CalendarTimesResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'timings': json['timings'] == null ? undefined : Model200CalendarTimesResponseDataTimingsFromJSON(json['timings']),
    };
}

export function Model200CalendarTimesResponseDataToJSON(json: any): Model200CalendarTimesResponseData {
    return Model200CalendarTimesResponseDataToJSONTyped(json, false);
}

export function Model200CalendarTimesResponseDataToJSONTyped(value?: Model200CalendarTimesResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timings': Model200CalendarTimesResponseDataTimingsToJSON(value['timings']),
    };
}

