/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200CalendarTimesResponseData } from './Model200CalendarTimesResponseData.js';
import {
    Model200CalendarTimesResponseDataFromJSON,
    Model200CalendarTimesResponseDataFromJSONTyped,
    Model200CalendarTimesResponseDataToJSON,
    Model200CalendarTimesResponseDataToJSONTyped,
} from './Model200CalendarTimesResponseData.js';

/**
 * 
 * @export
 * @interface Model200CalendarTimesResponse
 */
export interface Model200CalendarTimesResponse {
    /**
     * 
     * @type {number}
     * @memberof Model200CalendarTimesResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200CalendarTimesResponse
     */
    status?: string;
    /**
     * 
     * @type {Model200CalendarTimesResponseData}
     * @memberof Model200CalendarTimesResponse
     */
    data?: Model200CalendarTimesResponseData;
}

/**
 * Check if a given object implements the Model200CalendarTimesResponse interface.
 */
export function instanceOfModel200CalendarTimesResponse(value: object): value is Model200CalendarTimesResponse {
    return true;
}

export function Model200CalendarTimesResponseFromJSON(json: any): Model200CalendarTimesResponse {
    return Model200CalendarTimesResponseFromJSONTyped(json, false);
}

export function Model200CalendarTimesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200CalendarTimesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : Model200CalendarTimesResponseDataFromJSON(json['data']),
    };
}

export function Model200CalendarTimesResponseToJSON(json: any): Model200CalendarTimesResponse {
    return Model200CalendarTimesResponseToJSONTyped(json, false);
}

export function Model200CalendarTimesResponseToJSONTyped(value?: Model200CalendarTimesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': Model200CalendarTimesResponseDataToJSON(value['data']),
    };
}

