/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataJORDANLocation } from './Model200PrayerCalMethodsResponseDataJORDANLocation.js';
import {
    Model200PrayerCalMethodsResponseDataJORDANLocationFromJSON,
    Model200PrayerCalMethodsResponseDataJORDANLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJORDANLocationToJSON,
    Model200PrayerCalMethodsResponseDataJORDANLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJORDANLocation.js';
import type { Model200PrayerCalMethodsResponseDataJORDANParams } from './Model200PrayerCalMethodsResponseDataJORDANParams.js';
import {
    Model200PrayerCalMethodsResponseDataJORDANParamsFromJSON,
    Model200PrayerCalMethodsResponseDataJORDANParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataJORDANParamsToJSON,
    Model200PrayerCalMethodsResponseDataJORDANParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataJORDANParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataJORDAN
 */
export interface Model200PrayerCalMethodsResponseDataJORDAN {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataJORDAN
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataJORDAN
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJORDANParams}
     * @memberof Model200PrayerCalMethodsResponseDataJORDAN
     */
    params?: Model200PrayerCalMethodsResponseDataJORDANParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataJORDANLocation}
     * @memberof Model200PrayerCalMethodsResponseDataJORDAN
     */
    location?: Model200PrayerCalMethodsResponseDataJORDANLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataJORDAN interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataJORDAN(value: object): value is Model200PrayerCalMethodsResponseDataJORDAN {
    return true;
}

export function Model200PrayerCalMethodsResponseDataJORDANFromJSON(json: any): Model200PrayerCalMethodsResponseDataJORDAN {
    return Model200PrayerCalMethodsResponseDataJORDANFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJORDANFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataJORDAN {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataJORDANParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataJORDANLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataJORDANToJSON(json: any): Model200PrayerCalMethodsResponseDataJORDAN {
    return Model200PrayerCalMethodsResponseDataJORDANToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataJORDANToJSONTyped(value?: Model200PrayerCalMethodsResponseDataJORDAN | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataJORDANParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataJORDANLocationToJSON(value['location']),
    };
}

