/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataSINGAPORELocation } from './Model200PrayerCalMethodsResponseDataSINGAPORELocation.js';
import {
    Model200PrayerCalMethodsResponseDataSINGAPORELocationFromJSON,
    Model200PrayerCalMethodsResponseDataSINGAPORELocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataSINGAPORELocationToJSON,
    Model200PrayerCalMethodsResponseDataSINGAPORELocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataSINGAPORELocation.js';
import type { Model200PrayerCalMethodsResponseDataSINGAPOREParams } from './Model200PrayerCalMethodsResponseDataSINGAPOREParams.js';
import {
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSON,
    Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataSINGAPOREParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataSINGAPORE
 */
export interface Model200PrayerCalMethodsResponseDataSINGAPORE {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataSINGAPORE
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataSINGAPORE
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataSINGAPOREParams}
     * @memberof Model200PrayerCalMethodsResponseDataSINGAPORE
     */
    params?: Model200PrayerCalMethodsResponseDataSINGAPOREParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataSINGAPORELocation}
     * @memberof Model200PrayerCalMethodsResponseDataSINGAPORE
     */
    location?: Model200PrayerCalMethodsResponseDataSINGAPORELocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataSINGAPORE interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataSINGAPORE(value: object): value is Model200PrayerCalMethodsResponseDataSINGAPORE {
    return true;
}

export function Model200PrayerCalMethodsResponseDataSINGAPOREFromJSON(json: any): Model200PrayerCalMethodsResponseDataSINGAPORE {
    return Model200PrayerCalMethodsResponseDataSINGAPOREFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataSINGAPOREFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataSINGAPORE {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataSINGAPOREParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataSINGAPORELocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataSINGAPOREToJSON(json: any): Model200PrayerCalMethodsResponseDataSINGAPORE {
    return Model200PrayerCalMethodsResponseDataSINGAPOREToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataSINGAPOREToJSONTyped(value?: Model200PrayerCalMethodsResponseDataSINGAPORE | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataSINGAPOREParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataSINGAPORELocationToJSON(value['location']),
    };
}

