/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataPORTUGALParams } from './Model200PrayerCalMethodsResponseDataPORTUGALParams.js';
import {
    Model200PrayerCalMethodsResponseDataPORTUGALParamsFromJSON,
    Model200PrayerCalMethodsResponseDataPORTUGALParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataPORTUGALParamsToJSON,
    Model200PrayerCalMethodsResponseDataPORTUGALParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataPORTUGALParams.js';
import type { Model200PrayerCalMethodsResponseDataPORTUGALLocation } from './Model200PrayerCalMethodsResponseDataPORTUGALLocation.js';
import {
    Model200PrayerCalMethodsResponseDataPORTUGALLocationFromJSON,
    Model200PrayerCalMethodsResponseDataPORTUGALLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataPORTUGALLocationToJSON,
    Model200PrayerCalMethodsResponseDataPORTUGALLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataPORTUGALLocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataPORTUGAL
 */
export interface Model200PrayerCalMethodsResponseDataPORTUGAL {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataPORTUGAL
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataPORTUGAL
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataPORTUGALParams}
     * @memberof Model200PrayerCalMethodsResponseDataPORTUGAL
     */
    params?: Model200PrayerCalMethodsResponseDataPORTUGALParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataPORTUGALLocation}
     * @memberof Model200PrayerCalMethodsResponseDataPORTUGAL
     */
    location?: Model200PrayerCalMethodsResponseDataPORTUGALLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataPORTUGAL interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataPORTUGAL(value: object): value is Model200PrayerCalMethodsResponseDataPORTUGAL {
    return true;
}

export function Model200PrayerCalMethodsResponseDataPORTUGALFromJSON(json: any): Model200PrayerCalMethodsResponseDataPORTUGAL {
    return Model200PrayerCalMethodsResponseDataPORTUGALFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataPORTUGALFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataPORTUGAL {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataPORTUGALParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataPORTUGALLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataPORTUGALToJSON(json: any): Model200PrayerCalMethodsResponseDataPORTUGAL {
    return Model200PrayerCalMethodsResponseDataPORTUGALToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataPORTUGALToJSONTyped(value?: Model200PrayerCalMethodsResponseDataPORTUGAL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataPORTUGALParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataPORTUGALLocationToJSON(value['location']),
    };
}

