/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataCUSTOM
 */
export interface Model200PrayerCalMethodsResponseDataCUSTOM {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataCUSTOM
     */
    id?: number;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataCUSTOM interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataCUSTOM(value: object): value is Model200PrayerCalMethodsResponseDataCUSTOM {
    return true;
}

export function Model200PrayerCalMethodsResponseDataCUSTOMFromJSON(json: any): Model200PrayerCalMethodsResponseDataCUSTOM {
    return Model200PrayerCalMethodsResponseDataCUSTOMFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataCUSTOMFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataCUSTOM {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function Model200PrayerCalMethodsResponseDataCUSTOMToJSON(json: any): Model200PrayerCalMethodsResponseDataCUSTOM {
    return Model200PrayerCalMethodsResponseDataCUSTOMToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataCUSTOMToJSONTyped(value?: Model200PrayerCalMethodsResponseDataCUSTOM | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

