/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataKARACHIParams } from './Model200PrayerCalMethodsResponseDataKARACHIParams.js';
import {
    Model200PrayerCalMethodsResponseDataKARACHIParamsFromJSON,
    Model200PrayerCalMethodsResponseDataKARACHIParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataKARACHIParamsToJSON,
    Model200PrayerCalMethodsResponseDataKARACHIParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataKARACHIParams.js';
import type { Model200PrayerCalMethodsResponseDataTUNISIALocation } from './Model200PrayerCalMethodsResponseDataTUNISIALocation.js';
import {
    Model200PrayerCalMethodsResponseDataTUNISIALocationFromJSON,
    Model200PrayerCalMethodsResponseDataTUNISIALocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataTUNISIALocationToJSON,
    Model200PrayerCalMethodsResponseDataTUNISIALocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataTUNISIALocation.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataTUNISIA
 */
export interface Model200PrayerCalMethodsResponseDataTUNISIA {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataTUNISIA
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataTUNISIA
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataKARACHIParams}
     * @memberof Model200PrayerCalMethodsResponseDataTUNISIA
     */
    params?: Model200PrayerCalMethodsResponseDataKARACHIParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataTUNISIALocation}
     * @memberof Model200PrayerCalMethodsResponseDataTUNISIA
     */
    location?: Model200PrayerCalMethodsResponseDataTUNISIALocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataTUNISIA interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataTUNISIA(value: object): value is Model200PrayerCalMethodsResponseDataTUNISIA {
    return true;
}

export function Model200PrayerCalMethodsResponseDataTUNISIAFromJSON(json: any): Model200PrayerCalMethodsResponseDataTUNISIA {
    return Model200PrayerCalMethodsResponseDataTUNISIAFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataTUNISIAFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataTUNISIA {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataKARACHIParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataTUNISIALocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataTUNISIAToJSON(json: any): Model200PrayerCalMethodsResponseDataTUNISIA {
    return Model200PrayerCalMethodsResponseDataTUNISIAToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataTUNISIAToJSONTyped(value?: Model200PrayerCalMethodsResponseDataTUNISIA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataKARACHIParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataTUNISIALocationToJSON(value['location']),
    };
}

