/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseData } from './Model200PrayerCalMethodsResponseData.js';
import {
    Model200PrayerCalMethodsResponseDataFromJSON,
    Model200PrayerCalMethodsResponseDataFromJSONTyped,
    Model200PrayerCalMethodsResponseDataToJSON,
    Model200PrayerCalMethodsResponseDataToJSONTyped,
} from './Model200PrayerCalMethodsResponseData.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponse
 */
export interface Model200PrayerCalMethodsResponse {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponse
     */
    status?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseData}
     * @memberof Model200PrayerCalMethodsResponse
     */
    data?: Model200PrayerCalMethodsResponseData;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponse interface.
 */
export function instanceOfModel200PrayerCalMethodsResponse(value: object): value is Model200PrayerCalMethodsResponse {
    return true;
}

export function Model200PrayerCalMethodsResponseFromJSON(json: any): Model200PrayerCalMethodsResponse {
    return Model200PrayerCalMethodsResponseFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : Model200PrayerCalMethodsResponseDataFromJSON(json['data']),
    };
}

export function Model200PrayerCalMethodsResponseToJSON(json: any): Model200PrayerCalMethodsResponse {
    return Model200PrayerCalMethodsResponseToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseToJSONTyped(value?: Model200PrayerCalMethodsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'status': value['status'],
        'data': Model200PrayerCalMethodsResponseDataToJSON(value['data']),
    };
}

