/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Model200PrayerCalMethodsResponseDataEGYPTLocation } from './Model200PrayerCalMethodsResponseDataEGYPTLocation.js';
import {
    Model200PrayerCalMethodsResponseDataEGYPTLocationFromJSON,
    Model200PrayerCalMethodsResponseDataEGYPTLocationFromJSONTyped,
    Model200PrayerCalMethodsResponseDataEGYPTLocationToJSON,
    Model200PrayerCalMethodsResponseDataEGYPTLocationToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataEGYPTLocation.js';
import type { Model200PrayerCalMethodsResponseDataEGYPTParams } from './Model200PrayerCalMethodsResponseDataEGYPTParams.js';
import {
    Model200PrayerCalMethodsResponseDataEGYPTParamsFromJSON,
    Model200PrayerCalMethodsResponseDataEGYPTParamsFromJSONTyped,
    Model200PrayerCalMethodsResponseDataEGYPTParamsToJSON,
    Model200PrayerCalMethodsResponseDataEGYPTParamsToJSONTyped,
} from './Model200PrayerCalMethodsResponseDataEGYPTParams.js';

/**
 * 
 * @export
 * @interface Model200PrayerCalMethodsResponseDataEGYPT
 */
export interface Model200PrayerCalMethodsResponseDataEGYPT {
    /**
     * 
     * @type {number}
     * @memberof Model200PrayerCalMethodsResponseDataEGYPT
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model200PrayerCalMethodsResponseDataEGYPT
     */
    name?: string;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataEGYPTParams}
     * @memberof Model200PrayerCalMethodsResponseDataEGYPT
     */
    params?: Model200PrayerCalMethodsResponseDataEGYPTParams;
    /**
     * 
     * @type {Model200PrayerCalMethodsResponseDataEGYPTLocation}
     * @memberof Model200PrayerCalMethodsResponseDataEGYPT
     */
    location?: Model200PrayerCalMethodsResponseDataEGYPTLocation;
}

/**
 * Check if a given object implements the Model200PrayerCalMethodsResponseDataEGYPT interface.
 */
export function instanceOfModel200PrayerCalMethodsResponseDataEGYPT(value: object): value is Model200PrayerCalMethodsResponseDataEGYPT {
    return true;
}

export function Model200PrayerCalMethodsResponseDataEGYPTFromJSON(json: any): Model200PrayerCalMethodsResponseDataEGYPT {
    return Model200PrayerCalMethodsResponseDataEGYPTFromJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataEGYPTFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model200PrayerCalMethodsResponseDataEGYPT {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'params': json['params'] == null ? undefined : Model200PrayerCalMethodsResponseDataEGYPTParamsFromJSON(json['params']),
        'location': json['location'] == null ? undefined : Model200PrayerCalMethodsResponseDataEGYPTLocationFromJSON(json['location']),
    };
}

export function Model200PrayerCalMethodsResponseDataEGYPTToJSON(json: any): Model200PrayerCalMethodsResponseDataEGYPT {
    return Model200PrayerCalMethodsResponseDataEGYPTToJSONTyped(json, false);
}

export function Model200PrayerCalMethodsResponseDataEGYPTToJSONTyped(value?: Model200PrayerCalMethodsResponseDataEGYPT | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'params': Model200PrayerCalMethodsResponseDataEGYPTParamsToJSON(value['params']),
        'location': Model200PrayerCalMethodsResponseDataEGYPTLocationToJSON(value['location']),
    };
}

