/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  InlineObject,
  InlineObject1,
  Model200TimesPrayerTimesCalendarYearResponse,
} from '../models/index.js';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    Model200TimesPrayerTimesCalendarYearResponseFromJSON,
    Model200TimesPrayerTimesCalendarYearResponseToJSON,
} from '../models/index.js';

export interface AnnualPrayerTimesCalendarYearForRequest {
    year: number;
    latitude: string;
    longitude: string;
    method?: AnnualPrayerTimesCalendarYearForMethodEnum;
    shafaq?: AnnualPrayerTimesCalendarYearForShafaqEnum;
    tune?: string;
    school?: AnnualPrayerTimesCalendarYearForSchoolEnum;
    midnightMode?: AnnualPrayerTimesCalendarYearForMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: AnnualPrayerTimesCalendarYearForLatitudeAdjustmentMethodEnum;
    calendarMethod?: AnnualPrayerTimesCalendarYearForCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface CalendarPrayerTimesYearForAddressRequest {
    year: number;
    address: string;
    x7xapikey?: string;
    method?: CalendarPrayerTimesYearForAddressMethodEnum;
    shafaq?: CalendarPrayerTimesYearForAddressShafaqEnum;
    tune?: string;
    school?: CalendarPrayerTimesYearForAddressSchoolEnum;
    midnightMode?: CalendarPrayerTimesYearForAddressMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: CalendarPrayerTimesYearForAddressLatitudeAdjustmentMethodEnum;
    calendarMethod?: CalendarPrayerTimesYearForAddressCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface HijriPrayerTimesCalendarYearForAddressRequest {
    year: number;
    address: string;
    x7xapikey?: string;
    method?: HijriPrayerTimesCalendarYearForAddressMethodEnum;
    shafaq?: HijriPrayerTimesCalendarYearForAddressShafaqEnum;
    tune?: string;
    school?: HijriPrayerTimesCalendarYearForAddressSchoolEnum;
    midnightMode?: HijriPrayerTimesCalendarYearForAddressMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: HijriPrayerTimesCalendarYearForAddressLatitudeAdjustmentMethodEnum;
    calendarMethod?: HijriPrayerTimesCalendarYearForAddressCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface PrayerTimesCalendarYearForRequest {
    year: number;
    latitude: string;
    longitude: string;
    method?: PrayerTimesCalendarYearForMethodEnum;
    shafaq?: PrayerTimesCalendarYearForShafaqEnum;
    tune?: string;
    school?: PrayerTimesCalendarYearForSchoolEnum;
    midnightMode?: PrayerTimesCalendarYearForMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: PrayerTimesCalendarYearForLatitudeAdjustmentMethodEnum;
    calendarMethod?: PrayerTimesCalendarYearForCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface YearlyHijriCalendarPrayerTimesorCityCountryRequest {
    year: number;
    city: string;
    country: string;
    state?: string;
    x7xapikey?: string;
    method?: YearlyHijriCalendarPrayerTimesorCityCountryMethodEnum;
    shafaq?: YearlyHijriCalendarPrayerTimesorCityCountryShafaqEnum;
    tune?: string;
    school?: YearlyHijriCalendarPrayerTimesorCityCountrySchoolEnum;
    midnightMode?: YearlyHijriCalendarPrayerTimesorCityCountryMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: YearlyHijriCalendarPrayerTimesorCityCountryLatitudeAdjustmentMethodEnum;
    calendarMethod?: YearlyHijriCalendarPrayerTimesorCityCountryCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface YearlyPrayerTimesCalendarForCityRequest {
    year: number;
    city: string;
    country: string;
    state?: string;
    x7xapikey?: string;
    method?: YearlyPrayerTimesCalendarForCityMethodEnum;
    shafaq?: YearlyPrayerTimesCalendarForCityShafaqEnum;
    tune?: string;
    school?: YearlyPrayerTimesCalendarForCitySchoolEnum;
    midnightMode?: YearlyPrayerTimesCalendarForCityMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: YearlyPrayerTimesCalendarForCityLatitudeAdjustmentMethodEnum;
    calendarMethod?: YearlyPrayerTimesCalendarForCityCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
}

/**
 * 
 */
export class AnnualPrayerTimesCalendarApi extends runtime.BaseAPI {

    /**
     * Creates request options for annualPrayerTimesCalendarYearFor without sending the request
     */
    async annualPrayerTimesCalendarYearForRequestOpts(requestParameters: AnnualPrayerTimesCalendarYearForRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling annualPrayerTimesCalendarYearFor().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling annualPrayerTimesCalendarYearFor().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling annualPrayerTimesCalendarYearFor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/calendar/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Gregorian year
     * Prayer times for a Gregorian year
     */
    async annualPrayerTimesCalendarYearForRaw(requestParameters: AnnualPrayerTimesCalendarYearForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarYearResponse>> {
        const requestOptions = await this.annualPrayerTimesCalendarYearForRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarYearResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Gregorian year
     * Prayer times for a Gregorian year
     */
    async annualPrayerTimesCalendarYearFor(requestParameters: AnnualPrayerTimesCalendarYearForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarYearResponse> {
        const response = await this.annualPrayerTimesCalendarYearForRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for calendarPrayerTimesYearForAddress without sending the request
     */
    async calendarPrayerTimesYearForAddressRequestOpts(requestParameters: CalendarPrayerTimesYearForAddressRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling calendarPrayerTimesYearForAddress().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling calendarPrayerTimesYearForAddress().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/calendarByAddress/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Gregorian year for an address
     * Prayer times for a Gregorian year for an address
     */
    async calendarPrayerTimesYearForAddressRaw(requestParameters: CalendarPrayerTimesYearForAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarYearResponse>> {
        const requestOptions = await this.calendarPrayerTimesYearForAddressRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarYearResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Gregorian year for an address
     * Prayer times for a Gregorian year for an address
     */
    async calendarPrayerTimesYearForAddress(requestParameters: CalendarPrayerTimesYearForAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarYearResponse> {
        const response = await this.calendarPrayerTimesYearForAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for hijriPrayerTimesCalendarYearForAddress without sending the request
     */
    async hijriPrayerTimesCalendarYearForAddressRequestOpts(requestParameters: HijriPrayerTimesCalendarYearForAddressRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling hijriPrayerTimesCalendarYearForAddress().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling hijriPrayerTimesCalendarYearForAddress().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/hijriCalendarByAddress/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Hijri year for an address
     * Prayer times for a Hijri year for an address
     */
    async hijriPrayerTimesCalendarYearForAddressRaw(requestParameters: HijriPrayerTimesCalendarYearForAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarYearResponse>> {
        const requestOptions = await this.hijriPrayerTimesCalendarYearForAddressRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarYearResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Hijri year for an address
     * Prayer times for a Hijri year for an address
     */
    async hijriPrayerTimesCalendarYearForAddress(requestParameters: HijriPrayerTimesCalendarYearForAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarYearResponse> {
        const response = await this.hijriPrayerTimesCalendarYearForAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prayerTimesCalendarYearFor without sending the request
     */
    async prayerTimesCalendarYearForRequestOpts(requestParameters: PrayerTimesCalendarYearForRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling prayerTimesCalendarYearFor().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling prayerTimesCalendarYearFor().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling prayerTimesCalendarYearFor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/hijriCalendar/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Hijri year
     * Prayer times for a Hijri year
     */
    async prayerTimesCalendarYearForRaw(requestParameters: PrayerTimesCalendarYearForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarYearResponse>> {
        const requestOptions = await this.prayerTimesCalendarYearForRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarYearResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Hijri year
     * Prayer times for a Hijri year
     */
    async prayerTimesCalendarYearFor(requestParameters: PrayerTimesCalendarYearForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarYearResponse> {
        const response = await this.prayerTimesCalendarYearForRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for yearlyHijriCalendarPrayerTimesorCityCountry without sending the request
     */
    async yearlyHijriCalendarPrayerTimesorCityCountryRequestOpts(requestParameters: YearlyHijriCalendarPrayerTimesorCityCountryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling yearlyHijriCalendarPrayerTimesorCityCountry().'
            );
        }

        if (requestParameters['city'] == null) {
            throw new runtime.RequiredError(
                'city',
                'Required parameter "city" was null or undefined when calling yearlyHijriCalendarPrayerTimesorCityCountry().'
            );
        }

        if (requestParameters['country'] == null) {
            throw new runtime.RequiredError(
                'country',
                'Required parameter "country" was null or undefined when calling yearlyHijriCalendarPrayerTimesorCityCountry().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/hijriCalendarByCity/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times a Hijri year for a city and country
     * Prayer times for a Hijri year for a city and country
     */
    async yearlyHijriCalendarPrayerTimesorCityCountryRaw(requestParameters: YearlyHijriCalendarPrayerTimesorCityCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarYearResponse>> {
        const requestOptions = await this.yearlyHijriCalendarPrayerTimesorCityCountryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarYearResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times a Hijri year for a city and country
     * Prayer times for a Hijri year for a city and country
     */
    async yearlyHijriCalendarPrayerTimesorCityCountry(requestParameters: YearlyHijriCalendarPrayerTimesorCityCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarYearResponse> {
        const response = await this.yearlyHijriCalendarPrayerTimesorCityCountryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for yearlyPrayerTimesCalendarForCity without sending the request
     */
    async yearlyPrayerTimesCalendarForCityRequestOpts(requestParameters: YearlyPrayerTimesCalendarForCityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling yearlyPrayerTimesCalendarForCity().'
            );
        }

        if (requestParameters['city'] == null) {
            throw new runtime.RequiredError(
                'city',
                'Required parameter "city" was null or undefined when calling yearlyPrayerTimesCalendarForCity().'
            );
        }

        if (requestParameters['country'] == null) {
            throw new runtime.RequiredError(
                'country',
                'Required parameter "country" was null or undefined when calling yearlyPrayerTimesCalendarForCity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/calendarByCity/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times a Gregorian year for a city and country
     * Prayer times for a Gregorian year for a city and country
     */
    async yearlyPrayerTimesCalendarForCityRaw(requestParameters: YearlyPrayerTimesCalendarForCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarYearResponse>> {
        const requestOptions = await this.yearlyPrayerTimesCalendarForCityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarYearResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times a Gregorian year for a city and country
     * Prayer times for a Gregorian year for a city and country
     */
    async yearlyPrayerTimesCalendarForCity(requestParameters: YearlyPrayerTimesCalendarForCityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarYearResponse> {
        const response = await this.yearlyPrayerTimesCalendarForCityRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum AnnualPrayerTimesCalendarYearForMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum AnnualPrayerTimesCalendarYearForShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum AnnualPrayerTimesCalendarYearForSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum AnnualPrayerTimesCalendarYearForMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum AnnualPrayerTimesCalendarYearForLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum AnnualPrayerTimesCalendarYearForCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum CalendarPrayerTimesYearForAddressMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum CalendarPrayerTimesYearForAddressShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum CalendarPrayerTimesYearForAddressSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum CalendarPrayerTimesYearForAddressMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum CalendarPrayerTimesYearForAddressLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum CalendarPrayerTimesYearForAddressCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarYearForAddressMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarYearForAddressShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarYearForAddressSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarYearForAddressMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarYearForAddressLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarYearForAddressCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarYearForMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarYearForShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarYearForSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarYearForMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarYearForLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarYearForCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyHijriCalendarPrayerTimesorCityCountryMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyHijriCalendarPrayerTimesorCityCountryShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyHijriCalendarPrayerTimesorCityCountrySchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyHijriCalendarPrayerTimesorCityCountryMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyHijriCalendarPrayerTimesorCityCountryLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyHijriCalendarPrayerTimesorCityCountryCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyPrayerTimesCalendarForCityMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyPrayerTimesCalendarForCityShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyPrayerTimesCalendarForCitySchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyPrayerTimesCalendarForCityMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyPrayerTimesCalendarForCityLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum YearlyPrayerTimesCalendarForCityCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
