/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  DailyPrayerTimesForAddressOnDate400Response,
  DailyPrayerTimesForCityOnDate400Response,
  InlineObject,
  Model200TimesNextPrayerResponse,
  Model200TimesResponse,
  NextPrayerTimeForAddressOnDate400Response,
} from '../models/index.js';
import {
    DailyPrayerTimesForAddressOnDate400ResponseFromJSON,
    DailyPrayerTimesForAddressOnDate400ResponseToJSON,
    DailyPrayerTimesForCityOnDate400ResponseFromJSON,
    DailyPrayerTimesForCityOnDate400ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    Model200TimesNextPrayerResponseFromJSON,
    Model200TimesNextPrayerResponseToJSON,
    Model200TimesResponseFromJSON,
    Model200TimesResponseToJSON,
    NextPrayerTimeForAddressOnDate400ResponseFromJSON,
    NextPrayerTimeForAddressOnDate400ResponseToJSON,
} from '../models/index.js';

export interface DailyPrayerTimesForAddressOnDateRequest {
    date: string;
    address: string;
    x7xapikey?: string;
    method?: DailyPrayerTimesForAddressOnDateMethodEnum;
    shafaq?: DailyPrayerTimesForAddressOnDateShafaqEnum;
    tune?: string;
    school?: DailyPrayerTimesForAddressOnDateSchoolEnum;
    midnightMode?: DailyPrayerTimesForAddressOnDateMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: DailyPrayerTimesForAddressOnDateLatitudeAdjustmentMethodEnum;
    calendarMethod?: DailyPrayerTimesForAddressOnDateCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface DailyPrayerTimesForCityOnDateRequest {
    date: string;
    city: string;
    country: string;
    state?: string;
    x7xapikey?: string;
    method?: DailyPrayerTimesForCityOnDateMethodEnum;
    shafaq?: DailyPrayerTimesForCityOnDateShafaqEnum;
    tune?: string;
    school?: DailyPrayerTimesForCityOnDateSchoolEnum;
    midnightMode?: DailyPrayerTimesForCityOnDateMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: DailyPrayerTimesForCityOnDateLatitudeAdjustmentMethodEnum;
    calendarMethod?: DailyPrayerTimesForCityOnDateCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface DailyPrayerTimesForDateRequest {
    date: string;
    latitude: string;
    longitude: string;
    method?: DailyPrayerTimesForDateMethodEnum;
    shafaq?: DailyPrayerTimesForDateShafaqEnum;
    tune?: string;
    school?: DailyPrayerTimesForDateSchoolEnum;
    midnightMode?: DailyPrayerTimesForDateMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: DailyPrayerTimesForDateLatitudeAdjustmentMethodEnum;
    calendarMethod?: DailyPrayerTimesForDateCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface NextPrayerTimeForAddressOnDateRequest {
    date: string;
    address: string;
    x7xapikey?: string;
    method?: NextPrayerTimeForAddressOnDateMethodEnum;
    shafaq?: NextPrayerTimeForAddressOnDateShafaqEnum;
    tune?: string;
    school?: NextPrayerTimeForAddressOnDateSchoolEnum;
    midnightMode?: NextPrayerTimeForAddressOnDateMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: NextPrayerTimeForAddressOnDateLatitudeAdjustmentMethodEnum;
    calendarMethod?: NextPrayerTimeForAddressOnDateCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface NextPrayerTimeForDateRequest {
    date: string;
    latitude: string;
    longitude: string;
    method?: NextPrayerTimeForDateMethodEnum;
    shafaq?: NextPrayerTimeForDateShafaqEnum;
    tune?: string;
    school?: NextPrayerTimeForDateSchoolEnum;
    midnightMode?: NextPrayerTimeForDateMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: NextPrayerTimeForDateLatitudeAdjustmentMethodEnum;
    calendarMethod?: NextPrayerTimeForDateCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

/**
 * 
 */
export class DailyPrayerTimesApi extends runtime.BaseAPI {

    /**
     * Creates request options for dailyPrayerTimesForAddressOnDate without sending the request
     */
    async dailyPrayerTimesForAddressOnDateRequestOpts(requestParameters: DailyPrayerTimesForAddressOnDateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling dailyPrayerTimesForAddressOnDate().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling dailyPrayerTimesForAddressOnDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/timingsByAddress/{date}`;
        urlPath = urlPath.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all prayer times for an address on a specific date
     * Prayer times for an address
     */
    async dailyPrayerTimesForAddressOnDateRaw(requestParameters: DailyPrayerTimesForAddressOnDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesResponse>> {
        const requestOptions = await this.dailyPrayerTimesForAddressOnDateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesResponseFromJSON(jsonValue));
    }

    /**
     * Returns all prayer times for an address on a specific date
     * Prayer times for an address
     */
    async dailyPrayerTimesForAddressOnDate(requestParameters: DailyPrayerTimesForAddressOnDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesResponse> {
        const response = await this.dailyPrayerTimesForAddressOnDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for dailyPrayerTimesForCityOnDate without sending the request
     */
    async dailyPrayerTimesForCityOnDateRequestOpts(requestParameters: DailyPrayerTimesForCityOnDateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling dailyPrayerTimesForCityOnDate().'
            );
        }

        if (requestParameters['city'] == null) {
            throw new runtime.RequiredError(
                'city',
                'Required parameter "city" was null or undefined when calling dailyPrayerTimesForCityOnDate().'
            );
        }

        if (requestParameters['country'] == null) {
            throw new runtime.RequiredError(
                'country',
                'Required parameter "country" was null or undefined when calling dailyPrayerTimesForCityOnDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/timingsByCity/{date}`;
        urlPath = urlPath.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all prayer times for a city on a specific date
     * Prayer times for a city on a specific date
     */
    async dailyPrayerTimesForCityOnDateRaw(requestParameters: DailyPrayerTimesForCityOnDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesResponse>> {
        const requestOptions = await this.dailyPrayerTimesForCityOnDateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesResponseFromJSON(jsonValue));
    }

    /**
     * Returns all prayer times for a city on a specific date
     * Prayer times for a city on a specific date
     */
    async dailyPrayerTimesForCityOnDate(requestParameters: DailyPrayerTimesForCityOnDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesResponse> {
        const response = await this.dailyPrayerTimesForCityOnDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for dailyPrayerTimesForDate without sending the request
     */
    async dailyPrayerTimesForDateRequestOpts(requestParameters: DailyPrayerTimesForDateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling dailyPrayerTimesForDate().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling dailyPrayerTimesForDate().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling dailyPrayerTimesForDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/timings/{date}`;
        urlPath = urlPath.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all prayer times for a specific date
     * Prayer times for a specific date
     */
    async dailyPrayerTimesForDateRaw(requestParameters: DailyPrayerTimesForDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesResponse>> {
        const requestOptions = await this.dailyPrayerTimesForDateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesResponseFromJSON(jsonValue));
    }

    /**
     * Returns all prayer times for a specific date
     * Prayer times for a specific date
     */
    async dailyPrayerTimesForDate(requestParameters: DailyPrayerTimesForDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesResponse> {
        const response = await this.dailyPrayerTimesForDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for nextPrayerTimeForAddressOnDate without sending the request
     */
    async nextPrayerTimeForAddressOnDateRequestOpts(requestParameters: NextPrayerTimeForAddressOnDateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling nextPrayerTimeForAddressOnDate().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling nextPrayerTimeForAddressOnDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/nextPrayerByAddress/{date}`;
        urlPath = urlPath.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns next prayer times for the given address on the specified date
     * Next prayer times for an address on the specific date
     */
    async nextPrayerTimeForAddressOnDateRaw(requestParameters: NextPrayerTimeForAddressOnDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesNextPrayerResponse>> {
        const requestOptions = await this.nextPrayerTimeForAddressOnDateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesNextPrayerResponseFromJSON(jsonValue));
    }

    /**
     * Returns next prayer times for the given address on the specified date
     * Next prayer times for an address on the specific date
     */
    async nextPrayerTimeForAddressOnDate(requestParameters: NextPrayerTimeForAddressOnDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesNextPrayerResponse> {
        const response = await this.nextPrayerTimeForAddressOnDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for nextPrayerTimeForDate without sending the request
     */
    async nextPrayerTimeForDateRequestOpts(requestParameters: NextPrayerTimeForDateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling nextPrayerTimeForDate().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling nextPrayerTimeForDate().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling nextPrayerTimeForDate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/nextPrayer/{date}`;
        urlPath = urlPath.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns next prayer time for a specific date
     * Next prayer time for a date
     */
    async nextPrayerTimeForDateRaw(requestParameters: NextPrayerTimeForDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesNextPrayerResponse>> {
        const requestOptions = await this.nextPrayerTimeForDateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesNextPrayerResponseFromJSON(jsonValue));
    }

    /**
     * Returns next prayer time for a specific date
     * Next prayer time for a date
     */
    async nextPrayerTimeForDate(requestParameters: NextPrayerTimeForDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesNextPrayerResponse> {
        const response = await this.nextPrayerTimeForDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForAddressOnDateMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForAddressOnDateShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForAddressOnDateSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForAddressOnDateMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForAddressOnDateLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForAddressOnDateCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForCityOnDateMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForCityOnDateShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForCityOnDateSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForCityOnDateMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForCityOnDateLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForCityOnDateCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForDateMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForDateShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForDateSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForDateMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForDateLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum DailyPrayerTimesForDateCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForAddressOnDateMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForAddressOnDateShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForAddressOnDateSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForAddressOnDateMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForAddressOnDateLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForAddressOnDateCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForDateMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForDateShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForDateSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForDateMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForDateLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum NextPrayerTimeForDateCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
