/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  DateRangePrayerTimesCalendar400Response,
  Model200TimesPrayerTimesCalendarMonthResponse,
  PrayerTimesCalendarBetweenDatesFor400Response,
} from '../models/index.js';
import {
    DateRangePrayerTimesCalendar400ResponseFromJSON,
    DateRangePrayerTimesCalendar400ResponseToJSON,
    Model200TimesPrayerTimesCalendarMonthResponseFromJSON,
    Model200TimesPrayerTimesCalendarMonthResponseToJSON,
    PrayerTimesCalendarBetweenDatesFor400ResponseFromJSON,
    PrayerTimesCalendarBetweenDatesFor400ResponseToJSON,
} from '../models/index.js';

export interface DateRangePrayerTimesCalendarRequest {
    start: string;
    end: string;
    address: string;
    x7xapikey?: string;
    method?: DateRangePrayerTimesCalendarMethodEnum;
    shafaq?: DateRangePrayerTimesCalendarShafaqEnum;
    tune?: string;
    school?: DateRangePrayerTimesCalendarSchoolEnum;
    midnightMode?: DateRangePrayerTimesCalendarMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: DateRangePrayerTimesCalendarLatitudeAdjustmentMethodEnum;
    calendarMethod?: DateRangePrayerTimesCalendarCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface PrayerTimesCalendarBetweenDatesForRequest {
    start: string;
    end: string;
    latitude: string;
    longitude: string;
    method?: PrayerTimesCalendarBetweenDatesForMethodEnum;
    shafaq?: PrayerTimesCalendarBetweenDatesForShafaqEnum;
    tune?: string;
    school?: PrayerTimesCalendarBetweenDatesForSchoolEnum;
    midnightMode?: PrayerTimesCalendarBetweenDatesForMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: PrayerTimesCalendarBetweenDatesForLatitudeAdjustmentMethodEnum;
    calendarMethod?: PrayerTimesCalendarBetweenDatesForCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

/**
 * 
 */
export class DateRangePrayerTimesCalendarApi extends runtime.BaseAPI {

    /**
     * Creates request options for dateRangePrayerTimesCalendar without sending the request
     */
    async dateRangePrayerTimesCalendarRequestOpts(requestParameters: DateRangePrayerTimesCalendarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling dateRangePrayerTimesCalendar().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling dateRangePrayerTimesCalendar().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling dateRangePrayerTimesCalendar().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/calendarByAddress/from/{start}/to/{end}`;
        urlPath = urlPath.replace(`{${"start"}}`, encodeURIComponent(String(requestParameters['start'])));
        urlPath = urlPath.replace(`{${"end"}}`, encodeURIComponent(String(requestParameters['end'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a prayer times calendar for an address for a given date range between start date and end date with a maximum date range difference of 11 months
     * Prayer times calendar for an address between 2 dates
     */
    async dateRangePrayerTimesCalendarRaw(requestParameters: DateRangePrayerTimesCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.dateRangePrayerTimesCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns a prayer times calendar for an address for a given date range between start date and end date with a maximum date range difference of 11 months
     * Prayer times calendar for an address between 2 dates
     */
    async dateRangePrayerTimesCalendar(requestParameters: DateRangePrayerTimesCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.dateRangePrayerTimesCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prayerTimesCalendarBetweenDatesFor without sending the request
     */
    async prayerTimesCalendarBetweenDatesForRequestOpts(requestParameters: PrayerTimesCalendarBetweenDatesForRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling prayerTimesCalendarBetweenDatesFor().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling prayerTimesCalendarBetweenDatesFor().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling prayerTimesCalendarBetweenDatesFor().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling prayerTimesCalendarBetweenDatesFor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/calendar/from/{start}/to/{end}`;
        urlPath = urlPath.replace(`{${"start"}}`, encodeURIComponent(String(requestParameters['start'])));
        urlPath = urlPath.replace(`{${"end"}}`, encodeURIComponent(String(requestParameters['end'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a prayer times calendar for a date range between a start date and end date with a maximum date range difference of 11 months
     * Prayer times calendar between 2 dates
     */
    async prayerTimesCalendarBetweenDatesForRaw(requestParameters: PrayerTimesCalendarBetweenDatesForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.prayerTimesCalendarBetweenDatesForRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns a prayer times calendar for a date range between a start date and end date with a maximum date range difference of 11 months
     * Prayer times calendar between 2 dates
     */
    async prayerTimesCalendarBetweenDatesFor(requestParameters: PrayerTimesCalendarBetweenDatesForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.prayerTimesCalendarBetweenDatesForRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum DateRangePrayerTimesCalendarMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum DateRangePrayerTimesCalendarShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum DateRangePrayerTimesCalendarSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DateRangePrayerTimesCalendarMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum DateRangePrayerTimesCalendarLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum DateRangePrayerTimesCalendarCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarBetweenDatesForMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarBetweenDatesForShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarBetweenDatesForSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarBetweenDatesForMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarBetweenDatesForLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarBetweenDatesForCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
