/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  InlineObject,
  InlineObject1,
  Model200TimesPrayerTimesCalendarMonthResponse,
} from '../models/index.js';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    Model200TimesPrayerTimesCalendarMonthResponseFromJSON,
    Model200TimesPrayerTimesCalendarMonthResponseToJSON,
} from '../models/index.js';

export interface HijriPrayerTimesCalendarMonthForAddressRequest {
    year: number;
    month: number;
    address: string;
    x7xapikey?: string;
    method?: HijriPrayerTimesCalendarMonthForAddressMethodEnum;
    shafaq?: HijriPrayerTimesCalendarMonthForAddressShafaqEnum;
    tune?: string;
    school?: HijriPrayerTimesCalendarMonthForAddressSchoolEnum;
    midnightMode?: HijriPrayerTimesCalendarMonthForAddressMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: HijriPrayerTimesCalendarMonthForAddressLatitudeAdjustmentMethodEnum;
    calendarMethod?: HijriPrayerTimesCalendarMonthForAddressCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface HijriPrayerTimesCalendarMonthForCityCountryRequest {
    year: number;
    month: number;
    city: string;
    country: string;
    state?: string;
    x7xapikey?: string;
    method?: HijriPrayerTimesCalendarMonthForCityCountryMethodEnum;
    shafaq?: HijriPrayerTimesCalendarMonthForCityCountryShafaqEnum;
    tune?: string;
    school?: HijriPrayerTimesCalendarMonthForCityCountrySchoolEnum;
    midnightMode?: HijriPrayerTimesCalendarMonthForCityCountryMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: HijriPrayerTimesCalendarMonthForCityCountryLatitudeAdjustmentMethodEnum;
    calendarMethod?: HijriPrayerTimesCalendarMonthForCityCountryCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface MonthlyPrayerTimesCalendarRequest {
    year: number;
    month: number;
    address: string;
    x7xapikey?: string;
    method?: MonthlyPrayerTimesCalendarMethodEnum;
    shafaq?: MonthlyPrayerTimesCalendarShafaqEnum;
    tune?: string;
    school?: MonthlyPrayerTimesCalendarSchoolEnum;
    midnightMode?: MonthlyPrayerTimesCalendarMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: MonthlyPrayerTimesCalendarLatitudeAdjustmentMethodEnum;
    calendarMethod?: MonthlyPrayerTimesCalendarCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface MonthlyPrayerTimesCalendarMonthForRequest {
    year: number;
    month: number;
    latitude: string;
    longitude: string;
    method?: MonthlyPrayerTimesCalendarMonthForMethodEnum;
    shafaq?: MonthlyPrayerTimesCalendarMonthForShafaqEnum;
    tune?: string;
    school?: MonthlyPrayerTimesCalendarMonthForSchoolEnum;
    midnightMode?: MonthlyPrayerTimesCalendarMonthForMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: MonthlyPrayerTimesCalendarMonthForLatitudeAdjustmentMethodEnum;
    calendarMethod?: MonthlyPrayerTimesCalendarMonthForCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

export interface PrayerTimesCalendarMonthForRequest {
    year: number;
    month: number;
    latitude: string;
    longitude: string;
    method?: PrayerTimesCalendarMonthForMethodEnum;
    shafaq?: PrayerTimesCalendarMonthForShafaqEnum;
    tune?: string;
    school?: PrayerTimesCalendarMonthForSchoolEnum;
    midnightMode?: PrayerTimesCalendarMonthForMidnightModeEnum;
    timezonestring?: string;
    latitudeAdjustmentMethod?: PrayerTimesCalendarMonthForLatitudeAdjustmentMethodEnum;
    calendarMethod?: PrayerTimesCalendarMonthForCalendarMethodEnum;
    adjustment?: number;
    iso8601?: boolean;
    acceptEncoding?: string;
}

/**
 * 
 */
export class MonthlyPrayerTimesCalendarApi extends runtime.BaseAPI {

    /**
     * Creates request options for hijriPrayerTimesCalendarMonthForAddress without sending the request
     */
    async hijriPrayerTimesCalendarMonthForAddressRequestOpts(requestParameters: HijriPrayerTimesCalendarMonthForAddressRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling hijriPrayerTimesCalendarMonthForAddress().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling hijriPrayerTimesCalendarMonthForAddress().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling hijriPrayerTimesCalendarMonthForAddress().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/hijriCalendarByAddress/{year}/{month}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Hijri month for an address
     * Prayer times for a Hijri month for an address
     */
    async hijriPrayerTimesCalendarMonthForAddressRaw(requestParameters: HijriPrayerTimesCalendarMonthForAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.hijriPrayerTimesCalendarMonthForAddressRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Hijri month for an address
     * Prayer times for a Hijri month for an address
     */
    async hijriPrayerTimesCalendarMonthForAddress(requestParameters: HijriPrayerTimesCalendarMonthForAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.hijriPrayerTimesCalendarMonthForAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for hijriPrayerTimesCalendarMonthForCityCountry without sending the request
     */
    async hijriPrayerTimesCalendarMonthForCityCountryRequestOpts(requestParameters: HijriPrayerTimesCalendarMonthForCityCountryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling hijriPrayerTimesCalendarMonthForCityCountry().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling hijriPrayerTimesCalendarMonthForCityCountry().'
            );
        }

        if (requestParameters['city'] == null) {
            throw new runtime.RequiredError(
                'city',
                'Required parameter "city" was null or undefined when calling hijriPrayerTimesCalendarMonthForCityCountry().'
            );
        }

        if (requestParameters['country'] == null) {
            throw new runtime.RequiredError(
                'country',
                'Required parameter "country" was null or undefined when calling hijriPrayerTimesCalendarMonthForCityCountry().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['city'] != null) {
            queryParameters['city'] = requestParameters['city'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country'] = requestParameters['country'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/hijriCalendarByCity/{year}/{month}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times a Hijri month for a city and country
     * Prayer times for a Hijri month for a city and country
     */
    async hijriPrayerTimesCalendarMonthForCityCountryRaw(requestParameters: HijriPrayerTimesCalendarMonthForCityCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.hijriPrayerTimesCalendarMonthForCityCountryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times a Hijri month for a city and country
     * Prayer times for a Hijri month for a city and country
     */
    async hijriPrayerTimesCalendarMonthForCityCountry(requestParameters: HijriPrayerTimesCalendarMonthForCityCountryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.hijriPrayerTimesCalendarMonthForCityCountryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for monthlyPrayerTimesCalendar without sending the request
     */
    async monthlyPrayerTimesCalendarRequestOpts(requestParameters: MonthlyPrayerTimesCalendarRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling monthlyPrayerTimesCalendar().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling monthlyPrayerTimesCalendar().'
            );
        }

        if (requestParameters['address'] == null) {
            throw new runtime.RequiredError(
                'address',
                'Required parameter "address" was null or undefined when calling monthlyPrayerTimesCalendar().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['address'] != null) {
            queryParameters['address'] = requestParameters['address'];
        }

        if (requestParameters['x7xapikey'] != null) {
            queryParameters['x7xapikey'] = requestParameters['x7xapikey'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/calendarByAddress/{year}/{month}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Gregorian month for an address
     * Prayer times for a Gregorian month for an address
     */
    async monthlyPrayerTimesCalendarRaw(requestParameters: MonthlyPrayerTimesCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.monthlyPrayerTimesCalendarRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Gregorian month for an address
     * Prayer times for a Gregorian month for an address
     */
    async monthlyPrayerTimesCalendar(requestParameters: MonthlyPrayerTimesCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.monthlyPrayerTimesCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for monthlyPrayerTimesCalendarMonthFor without sending the request
     */
    async monthlyPrayerTimesCalendarMonthForRequestOpts(requestParameters: MonthlyPrayerTimesCalendarMonthForRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling monthlyPrayerTimesCalendarMonthFor().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling monthlyPrayerTimesCalendarMonthFor().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling monthlyPrayerTimesCalendarMonthFor().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling monthlyPrayerTimesCalendarMonthFor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/calendar/{year}/{month}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a Gregorian month
     * Prayer times for a Gregorian month
     */
    async monthlyPrayerTimesCalendarMonthForRaw(requestParameters: MonthlyPrayerTimesCalendarMonthForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.monthlyPrayerTimesCalendarMonthForRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a Gregorian month
     * Prayer times for a Gregorian month
     */
    async monthlyPrayerTimesCalendarMonthFor(requestParameters: MonthlyPrayerTimesCalendarMonthForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.monthlyPrayerTimesCalendarMonthForRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for prayerTimesCalendarMonthFor without sending the request
     */
    async prayerTimesCalendarMonthForRequestOpts(requestParameters: PrayerTimesCalendarMonthForRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling prayerTimesCalendarMonthFor().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling prayerTimesCalendarMonthFor().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling prayerTimesCalendarMonthFor().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling prayerTimesCalendarMonthFor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['shafaq'] != null) {
            queryParameters['shafaq'] = requestParameters['shafaq'];
        }

        if (requestParameters['tune'] != null) {
            queryParameters['tune'] = requestParameters['tune'];
        }

        if (requestParameters['school'] != null) {
            queryParameters['school'] = requestParameters['school'];
        }

        if (requestParameters['midnightMode'] != null) {
            queryParameters['midnightMode'] = requestParameters['midnightMode'];
        }

        if (requestParameters['timezonestring'] != null) {
            queryParameters['timezonestring'] = requestParameters['timezonestring'];
        }

        if (requestParameters['latitudeAdjustmentMethod'] != null) {
            queryParameters['latitudeAdjustmentMethod'] = requestParameters['latitudeAdjustmentMethod'];
        }

        if (requestParameters['calendarMethod'] != null) {
            queryParameters['calendarMethod'] = requestParameters['calendarMethod'];
        }

        if (requestParameters['iso8601'] != null) {
            queryParameters['iso8601'] = requestParameters['iso8601'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptEncoding'] != null) {
            headerParameters['Accept-Encoding'] = String(requestParameters['acceptEncoding']);
        }


        let urlPath = `/hijriCalendar/{year}/{month}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month'])));
        urlPath = urlPath.replace(`{${"adjustment"}}`, encodeURIComponent(String(requestParameters['adjustment'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns Prayer times for a requested Hijri month
     * Prayer times for a Hijri month
     */
    async prayerTimesCalendarMonthForRaw(requestParameters: PrayerTimesCalendarMonthForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200TimesPrayerTimesCalendarMonthResponse>> {
        const requestOptions = await this.prayerTimesCalendarMonthForRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200TimesPrayerTimesCalendarMonthResponseFromJSON(jsonValue));
    }

    /**
     * Returns Prayer times for a requested Hijri month
     * Prayer times for a Hijri month
     */
    async prayerTimesCalendarMonthFor(requestParameters: PrayerTimesCalendarMonthForRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200TimesPrayerTimesCalendarMonthResponse> {
        const response = await this.prayerTimesCalendarMonthForRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForAddressMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForAddressShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForAddressSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForAddressMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForAddressLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForAddressCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForCityCountryMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForCityCountryShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForCityCountrySchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForCityCountryMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForCityCountryLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum HijriPrayerTimesCalendarMonthForCityCountryCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMonthForMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMonthForShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMonthForSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMonthForMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMonthForLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum MonthlyPrayerTimesCalendarMonthForCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarMonthForMethodEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13,
    NUMBER_14 = 14,
    NUMBER_15 = 15,
    NUMBER_16 = 16,
    NUMBER_17 = 17,
    NUMBER_18 = 18,
    NUMBER_19 = 19,
    NUMBER_20 = 20,
    NUMBER_21 = 21,
    NUMBER_22 = 22,
    NUMBER_23 = 23,
    NUMBER_99 = 99
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarMonthForShafaqEnum {
    General = 'general',
    Ahmer = 'ahmer',
    Abyad = 'abyad'
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarMonthForSchoolEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarMonthForMidnightModeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarMonthForLatitudeAdjustmentMethodEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
  * @export
  * @enum {string}
  */
export enum PrayerTimesCalendarMonthForCalendarMethodEnum {
    HjcoSa = 'HJCoSA',
    Uaq = 'UAQ',
    Diyanet = 'DIYANET',
    Mathematical = 'MATHEMATICAL'
}
