/* tslint:disable */
/* eslint-disable */
/**
 * Prayer Times API - AlAdhan
 * A RESTful API to get islamic prayer times for a given day, month or year.     The API has several endpoints to assist developers. All the endpoints return JSON and are available over `http` and `https`.     Please note that prayer timings might not always match your local mosque or government authority.      Their timings are likely tuned or adjusted. Please see `https://aladhan.com/calculation-methods` for more details.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Model200PrayerCalMethodsResponse,
} from '../models/index.js';
import {
    Model200PrayerCalMethodsResponseFromJSON,
    Model200PrayerCalMethodsResponseToJSON,
} from '../models/index.js';

/**
 * 
 */
export class PrayerTimeMethodsApi extends runtime.BaseAPI {

    /**
     * Creates request options for prayerTimesMethods without sending the request
     */
    async prayerTimesMethodsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/methods`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all the prayer times calculation methods supported by the AlAdhan API.
     * Prayer Times Methods
     */
    async prayerTimesMethodsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model200PrayerCalMethodsResponse>> {
        const requestOptions = await this.prayerTimesMethodsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model200PrayerCalMethodsResponseFromJSON(jsonValue));
    }

    /**
     * Returns all the prayer times calculation methods supported by the AlAdhan API.
     * Prayer Times Methods
     */
    async prayerTimesMethods(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model200PrayerCalMethodsResponse> {
        const response = await this.prayerTimesMethodsRaw(initOverrides);
        return await response.value();
    }

}
